/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
	bnam: {type: 3, name: `(string) Name: Name`},
	bsuf: {type: 3, name: `(string) EditorSuffix: Editor Suffix`},
	bcat: {type: 3, name: `(destructableCategory) category: Category`, singleline : true},
	btil: {type: 3, name: `(tilesetList) tilesets: Tilesets`, singleline : true},
	btsp: {type: 0, name: `(bool) tilesetSpecific: Has Tileset Specific Data`, singleline : true},
	bfil: {type: 3, name: `(model) file: Model File`, singleline : true},
	blit: {type: 0, name: `(bool) lightweight: Model File - Has Lightweight Model`, singleline : true},
	bflo: {type: 0, name: `(bool) fatLOS: Fat Line of Sight`, singleline : true},
	btxi: {type: 0, name: `(int) texID: Replaceable Texture ID`, singleline : true},
	btxf: {type: 3, name: `(texture) texFile: Replaceable Texture File`, singleline : true},
	buch: {type: 0, name: `(bool) useClickHelper: Show Helper Object for Selection`, singleline : true},
	bonc: {type: 0, name: `(bool) onCliffs: Placeable on Cliffs`, singleline : true},
	bonw: {type: 0, name: `(bool) onWater: Placeable on Water`, singleline : true},
	bcpd: {type: 0, name: `(bool) canPlaceDead: Show Dead Version in Palette`, singleline : true},
	bwal: {type: 0, name: `(bool) walkable: Is Walkable`, singleline : true},
	bclh: {type: 0, name: `(int) cliffHeight: Cliff Height`, singleline : true},
	btar: {type: 3, name: `(targetList) targType: Targeted As`, singleline : true},
	barm: {type: 3, name: `(armorType) armor: Armor Type`, singleline : true},
	bvar: {type: 0, name: `(int) numVar: Model File - Variations`, singleline : true},
	bhps: {type: 2, name: `(unreal) HP: Hit Points`, singleline : true},
	boch: {type: 2, name: `(unreal) occH: Occlusion Height`, singleline : true},
	bflh: {type: 2, name: `(unreal) flyH: Fly-Over Height`, singleline : true},
	bfxr: {type: 2, name: `(unreal) fixedRot: Fixed Rotation`, singleline : true},
	bsel: {type: 2, name: `(unreal) selSize: Selection Size - Editor`, singleline : true},
	bmis: {type: 2, name: `(unreal) minScale: Minimum Scale`, singleline : true},
	bmas: {type: 2, name: `(unreal) maxScale: Maximum Scale`, singleline : true},
	bcpr: {type: 0, name: `(bool) canPlaceRandScale: Can Place Random Scale`, singleline : true},
	bmap: {type: 2, name: `(unreal) maxPitch: Maximum Pitch Angle (degrees)`, singleline : true},
	bmar: {type: 2, name: `(unreal) maxRoll: Max Roll Angle (degrees)`, singleline : true},
	brad: {type: 2, name: `(unreal) radius: Elevation Sample Radius`, singleline : true},
	bfra: {type: 2, name: `(unreal) fogRadius: Fog Radius`, singleline : true},
	bfvi: {type: 0, name: `(bool) fogVis: Fog Visibility`, singleline : true},
	bptx: {type: 3, name: `(pathingTexture) pathTex: Pathing Texture`, singleline : true},
	bptd: {type: 3, name: `(pathingTexture) pathTexDeath: Pathing Texture (Dead)`, singleline : true},
	bdsn: {type: 3, name: `(soundLabel) deathSnd: Death`, singleline : true},
	bsnd: {type: 3, name: `(soundLabel) loopSound: Зацикленный звук`, singleline : true},
	bshd: {type: 3, name: `(shadowTexture) shadow: Shadow`, singleline : true},
	bsmm: {type: 0, name: `(bool) showInMM: Minimap - Show`, singleline : true},
	bmmr: {type: 0, name: `(int) MMRed: Minimap Color 1 (Red)`, singleline : true},
	bmmg: {type: 0, name: `(int) MMGreen: Minimap Color 2 (Green)`, singleline : true},
	bmmb: {type: 0, name: `(int) MMBlue: Minimap Color 3 (Blue)`, singleline : true},
	bumm: {type: 0, name: `(bool) useMMColor: Minimap - Use Custom Color`, singleline : true},
	bbut: {type: 0, name: `(int) buildTime: Build Time`, singleline : true},
	bret: {type: 0, name: `(int) repairTime: Repair Time`, singleline : true},
	breg: {type: 0, name: `(int) goldRep: Repair Gold Cost`, singleline : true},
	brel: {type: 0, name: `(int) lumberRep: Repair Lumber Cost`, singleline : true},
	busr: {type: 0, name: `(bool) UserList: On User-Specified List`, singleline : true},
	bvcr: {type: 0, name: `(int) colorR: Tinting Color 1 (Red)`, singleline : true},
	bvcg: {type: 0, name: `(int) colorG: Tinting Color 2 (Green)`, singleline : true},
	bvcb: {type: 0, name: `(int) colorB: Tinting Color 3 (Blue)`, singleline : true},
	bgse: {type: 0, name: `(bool) selectable: Selectable In Game`, singleline : true},
	bgsc: {type: 1, name: `(real) selcircsize: Selection Size - Game`, singleline : true},
	bgpm: {type: 3, name: `(model) portraitmodel: Model File - Portrait`, singleline : true},

};
export default map;