/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
	iabi: {type: 3, name: `(abilityList) abilList: Abilities`, singleline : true},
	iarm: {type: 3, name: `(armorType) armor: Armor Type`, singleline : true},
	icla: {type: 3, name: `(itemClass) class: Classification`, singleline : true},
	iclb: {type: 0, name: `(int) colorB: Tinting Color 3 (Blue)`, singleline : true},
	iclg: {type: 0, name: `(int) colorG: Tinting Color 2 (Green)`, singleline : true},
	iclr: {type: 0, name: `(int) colorR: Tinting Color 1 (Red)`, singleline : true},
	icid: {type: 3, name: `(abilCode) cooldownID: Cooldown Group`, singleline : true},
	idrp: {type: 0, name: `(bool) drop: Dropped When Carrier Dies`, singleline : true},
	idro: {type: 0, name: `(bool) droppable: Can Be Dropped`, singleline : true},
	ifil: {type: 3, name: `(model) file: Model Used`, singleline : true},
	igol: {type: 0, name: `(int) goldcost: Gold Cost`, singleline : true},
	ihtp: {type: 0, name: `(int) HP: Hit Points`, singleline : true},
	iicd: {type: 0, name: `(bool) ignoreCD: Ignore Cooldown`, singleline : true},
	ilev: {type: 0, name: `(int) Level: Level`, singleline : true},
	ilum: {type: 0, name: `(int) lumbercost: Lumber Cost`, singleline : true},
	imor: {type: 0, name: `(bool) morph: Valid Target For Transformation`, singleline : true},
	ilvo: {type: 0, name: `(int) oldLevel: Level (Unclassified)`, singleline : true},
	iper: {type: 0, name: `(bool) perishable: Perishable`, singleline : true},
	iprn: {type: 0, name: `(bool) pickRandom: Include As Random Choice`, singleline : true},
	ipow: {type: 0, name: `(bool) powerup: Use Automatically When Acquired`, singleline : true},
	ipri: {type: 0, name: `(int) prio: Priority`, singleline : true},
	isca: {type: 1, name: `(real) scale: Scaling Value`, singleline : true},
	issc: {type: 1, name: `(real) selSize: Selection Size - Editor`, singleline : true},
	isel: {type: 0, name: `(bool) sellable: Can Be Sold By Merchants`, singleline : true},
	ipaw: {type: 0, name: `(bool) pawnable: Can Be Sold To Merchants`, singleline : true},
	isto: {type: 0, name: `(int) stockMax: Stock Maximum`, singleline : true},
	istr: {type: 0, name: `(int) stockRegen: Stock Replenish Interval`, singleline : true},
	isst: {type: 0, name: `(int) stockStart: Stock Start Delay`, singleline : true},
	isit: {type: 0, name: `(int) stockInitial: Stock Initial After Start Delay`, singleline : true},
	iusa: {type: 0, name: `(bool) usable: Actively Used`, singleline : true},
	iuse: {type: 0, name: `(int) uses: Number of Charges`, singleline : true},
	ista: {type: 0, name: `(int) stackMax: Max Stacks`, singleline : true},
	uani: {type: 3, name: `(stringList) animProps: Required Animation Names`, singleline : true},
	uico: {type: 3, name: `(icon) Art: Icon - Game Interface`, singleline : true},
	iico: {type: 3, name: `(icon) Art: Interface Icon`, singleline : true},
	uaap: {type: 3, name: `(stringList) Attachmentanimprops: Required Animation Names - Attachments`, singleline : true},
	ualp: {type: 3, name: `(stringList) Attachmentlinkprops: Required Attachment Link Names`, singleline : true},
	uawt: {type: 3, name: `(string) Awakentip: Tooltip - Awaken`},
	ubpr: {type: 3, name: `(stringList) Boneprops: Required Bone Names`, singleline : true},
	ubsl: {type: 3, name: `(soundLabel) BuildingSoundLabel: Construction`, singleline : true},
	ubui: {type: 3, name: `(unitList) Builds: Structures Built`, singleline : true},
	ubpx: {type: 0, name: `(int) Buttonpos: Button Position (X)`, singleline : true},
	ubpy: {type: 0, name: `(int) Buttonpos: Button Position (Y)`, singleline : true},
	ucua: {type: 3, name: `(icon) Casterupgradeart: Caster Upgrade Art`, singleline : true},
	ucun: {type: 3, name: `(stringList) Casterupgradename: Caster Upgrade Names`, singleline : true},
	ucut: {type: 3, name: `(stringList) Casterupgradetip: Caster Upgrade Tips`, singleline : true},
	udep: {type: 3, name: `(unitList) DependencyOr: Dependency Equivalents`, singleline : true},
	ides: {type: 3, name: `(string) Description: Description`},
	unsf: {type: 3, name: `(string) EditorSuffix: Name - Editor Suffix`},
	uhot: {type: 3, name: `(char) Hotkey: Hotkey`, singleline : true},
	ulfi: {type: 0, name: `(int) LoopingSoundFadeIn: Looping Fade In Rate`, singleline : true},
	ulfo: {type: 0, name: `(int) LoopingSoundFadeOut: Looping Fade Out Rate`, singleline : true},
	umki: {type: 3, name: `(itemList) Makeitems: Items Made`, singleline : true},
	uma1: {type: 2, name: `(unreal) Missilearc: Attack 1 - Projectile Arc`, singleline : true},
	uma2: {type: 2, name: `(unreal) Missilearc: Attack 2 - Projectile Arc`, singleline : true},
	ua1m: {type: 3, name: `(model) Missileart: Attack 1 - Projectile Art`, singleline : true},
	ua2m: {type: 3, name: `(model) Missileart: Attack 2 - Projectile Art`, singleline : true},
	umh1: {type: 0, name: `(bool) MissileHoming: Attack 1 - Projectile Homing Enabled`, singleline : true},
	umh2: {type: 0, name: `(bool) MissileHoming: Attack 2 - Projectile Homing Enabled`, singleline : true},
	ua1z: {type: 0, name: `(int) Missilespeed: Attack 1 - Projectile Speed`, singleline : true},
	ua2z: {type: 0, name: `(int) Missilespeed: Attack 2 - Projectile Speed`, singleline : true},
	umsl: {type: 3, name: `(soundLabel) MovementSoundLabel: Movement`, singleline : true},
	unam: {type: 3, name: `(string) Name: Name`},
	upro: {type: 3, name: `(stringList) Propernames: Proper Names`, singleline : true},
	ursl: {type: 3, name: `(soundLabel) RandomSoundLabel: Random`, singleline : true},
	urqc: {type: 0, name: `(int) Requirescount: Requirements - Tiers Used`, singleline : true},
	ureq: {type: 3, name: `(techList) Requires: Requirements`, singleline : true},
	urq1: {type: 3, name: `(techList) Requires1: Requirements - Tier 2`, singleline : true},
	urq2: {type: 3, name: `(techList) Requires2: Requirements - Tier 3`, singleline : true},
	urq3: {type: 3, name: `(techList) Requires3: Requirements - Tier 4`, singleline : true},
	urq4: {type: 3, name: `(techList) Requires4: Requirements - Tier 5`, singleline : true},
	urq5: {type: 3, name: `(techList) Requires5: Requirements - Tier 6`, singleline : true},
	urq6: {type: 3, name: `(techList) Requires6: Requirements - Tier 7`, singleline : true},
	urq7: {type: 3, name: `(techList) Requires7: Requirements - Tier 8`, singleline : true},
	urq8: {type: 3, name: `(techList) Requires8: Requirements - Tier 9`, singleline : true},
	urqa: {type: 3, name: `(intList) Requiresamount: Requirements - Levels`, singleline : true},
	ures: {type: 3, name: `(upgradeList) Researches: Researches Available`, singleline : true},
	urev: {type: 0, name: `(bool) Revive: Revives Dead Heroes`, singleline : true},
	utpr: {type: 3, name: `(string) Revivetip: Tooltip - Revive`},
	ussi: {type: 3, name: `(icon) ScoreScreenIcon: Icon - Score Screen`, singleline : true},
	usei: {type: 3, name: `(itemList) Sellitems: Items Sold`, singleline : true},
	useu: {type: 3, name: `(unitList) Sellunits: Units Sold`, singleline : true},
	uspa: {type: 3, name: `(modelList) Specialart: Special`, singleline : true},
	utaa: {type: 3, name: `(modelList) Targetart: Target`, singleline : true},
	utip: {type: 3, name: `(string) Tip: Tooltip - Basic`},
	utra: {type: 3, name: `(unitList) Trains: Units Trained`, singleline : true},
	urva: {type: 3, name: `(unitList) Reviveat: Hero Revival Locations`, singleline : true},
	utub: {type: 3, name: `(string) Ubertip: Tooltip - Extended`},
	uupt: {type: 3, name: `(unitList) Upgrade: Upgrades To`, singleline : true},
	uabi: {type: 3, name: `(abilityList) abilList: Normal`, singleline : true},
	udaa: {type: 3, name: `(abilCode) auto: Default Active Ability`, singleline : true},
	uhab: {type: 3, name: `(heroAbilityList) heroAbilList: Hero`, singleline : true},
	uagi: {type: 0, name: `(int) AGI: Starting Agility`, singleline : true},
	uagp: {type: 2, name: `(unreal) AGIplus: Agility per Level`, singleline : true},
	ubld: {type: 0, name: `(int) bldtm: Build Time`, singleline : true},
	ubdi: {type: 0, name: `(int) bountydice: Gold Bounty Awarded - Number of Dice`, singleline : true},
	ubba: {type: 0, name: `(int) bountyplus: Gold Bounty Awarded - Base`, singleline : true},
	ubsi: {type: 0, name: `(int) bountysides: Gold Bounty Awarded - Sides per Die`, singleline : true},
	ulbd: {type: 0, name: `(int) lumberbountydice: Lumber Bounty Awarded - Number of Dice`, singleline : true},
	ulba: {type: 0, name: `(int) lumberbountyplus: Lumber Bounty Awarded - Base`, singleline : true},
	ulbs: {type: 0, name: `(int) lumberbountysides: Lumber Bounty Awarded - Sides per Die`, singleline : true},
	ucol: {type: 2, name: `(unreal) collision: Collision Size`, singleline : true},
	udef: {type: 0, name: `(int) def: Defense Base`, singleline : true},
	udty: {type: 3, name: `(defenseType) defType: Defense Type`, singleline : true},
	udup: {type: 0, name: `(int) defUp: Defense Upgrade Bonus`, singleline : true},
	ufma: {type: 0, name: `(int) fmade: Food Produced`, singleline : true},
	ufoo: {type: 0, name: `(int) fused: Food Cost`, singleline : true},
	ugol: {type: 0, name: `(int) goldcost: Gold Cost`, singleline : true},
	ugor: {type: 0, name: `(int) goldRep: Repair Gold Cost`, singleline : true},
	uhpm: {type: 0, name: `(int) HP: Hit Points Maximum (Base)`, singleline : true},
	uint: {type: 0, name: `(int) INT: Starting Intelligence`, singleline : true},
	uinp: {type: 2, name: `(unreal) INTplus: Intelligence per Level`, singleline : true},
	ubdg: {type: 0, name: `(bool) isbldg: Is a Building`, singleline : true},
	ulev: {type: 0, name: `(int) level: Level`, singleline : true},
	ulum: {type: 0, name: `(int) lumbercost: Lumber Cost`, singleline : true},
	ulur: {type: 0, name: `(int) lumberRep: Repair Lumber Cost`, singleline : true},
	umpi: {type: 0, name: `(int) mana0: Mana Initial Amount`, singleline : true},
	umpm: {type: 0, name: `(int) manaN: Mana Maximum`, singleline : true},
	umas: {type: 0, name: `(int) maxSpd: Speed Maximum`, singleline : true},
	umis: {type: 0, name: `(int) minSpd: Speed Minimum`, singleline : true},
	unbr: {type: 0, name: `(bool) nbrandom: Neutral Building - Valid As Random Building`, singleline : true},
	usin: {type: 0, name: `(int) nsight: Sight Radius (Night)`, singleline : true},
	upap: {type: 3, name: `(pathingListPrevent) preventPlace: Placement Requires`, singleline : true},
	upra: {type: 3, name: `(attributeType) Primary: Primary Attribute`, singleline : true},
	uhpr: {type: 2, name: `(unreal) regenHP: Hit Points Regeneration Rate`, singleline : true},
	umpr: {type: 2, name: `(unreal) regenMana: Mana Regeneration`, singleline : true},
	uhrt: {type: 3, name: `(regenType) regenType: Hit Points Regeneration Type`, singleline : true},
	urtm: {type: 0, name: `(int) reptm: Repair Time`, singleline : true},
	urpo: {type: 0, name: `(bool) repulse: Group Separation - Enabled`, singleline : true},
	urpg: {type: 0, name: `(int) repulseGroup: Group Separation - Group Number`, singleline : true},
	urpp: {type: 0, name: `(int) repulseParam: Group Separation - Parameter`, singleline : true},
	urpr: {type: 0, name: `(int) repulsePrio: Group Separation - Priority`, singleline : true},
	upar: {type: 3, name: `(pathingListRequire) requirePlace: Placement Prevented By`, singleline : true},
	usid: {type: 0, name: `(int) sight: Sight Radius (Day)`, singleline : true},
	umvs: {type: 0, name: `(int) spd: Speed Base`, singleline : true},
	usma: {type: 0, name: `(int) stockMax: Stock Maximum`, singleline : true},
	usrg: {type: 0, name: `(int) stockRegen: Stock Replenish Interval`, singleline : true},
	usst: {type: 0, name: `(int) stockStart: Stock Start Delay`, singleline : true},
	usit: {type: 0, name: `(int) stockInitial: Stock Initial After Start Delay`, singleline : true},
	ustr: {type: 0, name: `(int) STR: Starting Strength`, singleline : true},
	ustp: {type: 2, name: `(unreal) STRplus: Strength per Level`, singleline : true},
	util: {type: 3, name: `(tilesetList) tilesets: Tilesets`, singleline : true},
	utyp: {type: 3, name: `(unitClass) type: Unit Classification`, singleline : true},
	upgr: {type: 3, name: `(upgradeList) upgrades: Upgrades Used`, singleline : true},
	uabr: {type: 2, name: `(unreal) buffRadius: AI Placement Radius`, singleline : true},
	uabt: {type: 3, name: `(aiBuffer) buffType: AI Placement Type`, singleline : true},
	ucbo: {type: 0, name: `(bool) canBuildOn: Can Build On`, singleline : true},
	ufle: {type: 0, name: `(bool) canFlee: Can Flee`, singleline : true},
	usle: {type: 0, name: `(bool) canSleep: Sleeps`, singleline : true},
	ucar: {type: 0, name: `(int) cargoSize: Transported Size`, singleline : true},
	udtm: {type: 2, name: `(unreal) death: Death Time (seconds)`, singleline : true},
	udea: {type: 0, name: `(deathType) deathType: Death Type`, singleline : true},
	ulos: {type: 0, name: `(bool) fatLOS: Use Extended Line of Sight`, singleline : true},
	ufor: {type: 0, name: `(int) formation: Formation Rank`, singleline : true},
	uibo: {type: 0, name: `(bool) isBuildOn: Can Be Built On`, singleline : true},
	umvf: {type: 2, name: `(unreal) moveFloor: Height Minimum`, singleline : true},
	umvh: {type: 2, name: `(unreal) moveHeight: Height`, singleline : true},
	umvt: {type: 3, name: `(moveType) movetp: Type`, singleline : true},
	upru: {type: 0, name: `(int) nameCount: Proper Names Used`, singleline : true},
	uori: {type: 0, name: `(int) orientInterp: Orientation Interpolation`, singleline : true},
	upat: {type: 3, name: `(pathingTexture) pathTex: Pathing Map`, singleline : true},
	upoi: {type: 0, name: `(int) points: Point Value`, singleline : true},
	upri: {type: 0, name: `(int) prio: Priority`, singleline : true},
	uprw: {type: 2, name: `(unreal) propWin: Propulsion Window (degrees)`, singleline : true},
	urac: {type: 3, name: `(unitRace) race: Race`, singleline : true},
	upaw: {type: 2, name: `(unreal) requireWaterRadius: Placement Requires Water Radius`, singleline : true},
	utar: {type: 3, name: `(targetList) targType: Targeted as`, singleline : true},
	umvr: {type: 2, name: `(unreal) turnRate: Turn Rate`, singleline : true},
	uarm: {type: 3, name: `(armorType) armor: Armor Type`, singleline : true},
	uble: {type: 1, name: `(real) blend: Animation - Blend Time (seconds)`, singleline : true},
	uclb: {type: 0, name: `(int) blue: Tinting Color 3 (Blue)`, singleline : true},
	ushb: {type: 3, name: `(shadowTexture) buildingShadow: Shadow Texture (Building)`, singleline : true},
	ucam: {type: 0, name: `(bool) campaign: Categorization - Campaign`, singleline : true},
	utcc: {type: 0, name: `(bool) customTeamColor: Allow Custom Team Color`, singleline : true},
	udro: {type: 0, name: `(bool) dropItems: Can Drop Items On Death`, singleline : true},
	uept: {type: 0, name: `(int) elevPts: Elevation - Sample Points`, singleline : true},
	uerd: {type: 1, name: `(real) elevRad: Elevation - Sample Radius`, singleline : true},
	umdl: {type: 3, name: `(model) file: Model File`, singleline : true},
	uver: {type: 0, name: `(versionFlags) fileVerFlags: Model File - Extra Versions`, singleline : true},
	ufrd: {type: 1, name: `(real) fogRad: Fog of War - Sample Radius`, singleline : true},
	uclg: {type: 0, name: `(int) green: Tinting Color 2 (Green)`, singleline : true},
	uhos: {type: 0, name: `(bool) hostilePal: Display as Neutral Hostile`, singleline : true},
	uine: {type: 0, name: `(bool) inEditor: Placeable In Editor`, singleline : true},
	umxp: {type: 1, name: `(real) maxPitch: Maximum Pitch Angle (degrees)`, singleline : true},
	umxr: {type: 1, name: `(real) maxRoll: Maximum Roll Angle (degrees)`, singleline : true},
	usca: {type: 1, name: `(real) modelScale: Scaling Value`, singleline : true},
	unbm: {type: 0, name: `(bool) nbmmIcon: Neutral Building - Shows Minimap Icon`, singleline : true},
	uhhb: {type: 0, name: `(bool) hideHeroBar: Hero - Hide Hero Interface Icon`, singleline : true},
	uhhm: {type: 0, name: `(bool) hideHeroMinimap: Hero - Hide Hero Minimap Display`, singleline : true},
	uhhd: {type: 0, name: `(bool) hideHeroDeathMsg: Hero - Hide Hero Death Message`, singleline : true},
	uhom: {type: 0, name: `(bool) hideOnMinimap: Hide Minimap Display`, singleline : true},
	uocc: {type: 2, name: `(unreal) occH: Occluder Height`, singleline : true},
	uclr: {type: 0, name: `(int) red: Tinting Color 1 (Red)`, singleline : true},
	urun: {type: 1, name: `(real) run: Animation - Run Speed`, singleline : true},
	ussc: {type: 1, name: `(real) scale: Selection Scale`, singleline : true},
	uscb: {type: 0, name: `(bool) scaleBull: Scale Projectiles`, singleline : true},
	usew: {type: 0, name: `(bool) selCircOnWater: Selection Circle On Water`, singleline : true},
	uslz: {type: 1, name: `(real) selZ: Selection Circle - Height`, singleline : true},
	ushh: {type: 1, name: `(real) shadowH: Shadow Image - Height`, singleline : true},
	ushr: {type: 0, name: `(bool) shadowOnWater: Has Water Shadow`, singleline : true},
	ushw: {type: 1, name: `(real) shadowW: Shadow Image - Width`, singleline : true},
	ushx: {type: 1, name: `(real) shadowX: Shadow Image - Center X`, singleline : true},
	ushy: {type: 1, name: `(real) shadowY: Shadow Image - Center Y`, singleline : true},
	uspe: {type: 0, name: `(bool) special: Categorization - Special`, singleline : true},
	utco: {type: 0, name: `(teamColor) teamColor: Team Color`, singleline : true},
	utss: {type: 0, name: `(bool) tilesetSpecific: Has Tileset Specific Data`, singleline : true},
	uubs: {type: 3, name: `(uberSplat) uberSplat: Ground Texture`, singleline : true},
	ushu: {type: 3, name: `(shadowImage) unitShadow: Shadow Image (Unit)`, singleline : true},
	usnd: {type: 3, name: `(unitSound) unitSound: Unit Sound Set`, singleline : true},
	uuch: {type: 0, name: `(bool) useClickHelper: Use Click Helper`, singleline : true},
	uwal: {type: 1, name: `(real) walk: Animation - Walk Speed`, singleline : true},
	uacq: {type: 2, name: `(unreal) acquire: Acquisition Range`, singleline : true},
	ua1t: {type: 3, name: `(attackType) atkType1: Attack 1 - Attack Type`, singleline : true},
	ua2t: {type: 3, name: `(attackType) atkType2: Attack 2 - Attack Type`, singleline : true},
	ubs1: {type: 2, name: `(unreal) backSw1: Attack 1 - Animation Backswing Point`, singleline : true},
	ubs2: {type: 2, name: `(unreal) backSw2: Attack 2 - Animation Backswing Point`, singleline : true},
	ucbs: {type: 2, name: `(unreal) castbsw: Animation - Cast Backswing`, singleline : true},
	ucpt: {type: 2, name: `(unreal) castpt: Animation - Cast Point`, singleline : true},
	ua1c: {type: 2, name: `(unreal) cool1: Attack 1 - Cooldown Time`, singleline : true},
	ua2c: {type: 2, name: `(unreal) cool2: Attack 2 - Cooldown Time`, singleline : true},
	udl1: {type: 2, name: `(unreal) damageLoss1: Attack 1 - Damage Loss Factor`, singleline : true},
	udl2: {type: 2, name: `(unreal) damageLoss2: Attack 2 - Damage Loss Factor`, singleline : true},
	ua1d: {type: 0, name: `(int) dice1: Attack 1 - Damage Number of Dice`, singleline : true},
	ua2d: {type: 0, name: `(int) dice2: Attack 2 - Damage Number of Dice`, singleline : true},
	ua1b: {type: 0, name: `(int) dmgplus1: Attack 1 - Damage Base`, singleline : true},
	ua2b: {type: 0, name: `(int) dmgplus2: Attack 2 - Damage Base`, singleline : true},
	udp1: {type: 2, name: `(unreal) dmgpt1: Attack 1 - Animation Damage Point`, singleline : true},
	udp2: {type: 2, name: `(unreal) dmgpt2: Attack 2 - Animation Damage Point`, singleline : true},
	udu1: {type: 0, name: `(int) dmgUp1: Attack 1 - Damage Upgrade Amount`, singleline : true},
	udu2: {type: 0, name: `(int) dmgUp2: Attack 2 - Damage Upgrade Amount`, singleline : true},
	ua1f: {type: 0, name: `(int) Farea1: Attack 1 - Area of Effect (Full Damage)`, singleline : true},
	ua2f: {type: 0, name: `(int) Farea2: Attack 2 - Area of Effect (Full Damage)`, singleline : true},
	ua1h: {type: 0, name: `(int) Harea1: Attack 1 - Area of Effect (Medium Damage)`, singleline : true},
	ua2h: {type: 0, name: `(int) Harea2: Attack 2 - Area of Effect (Medium Damage)`, singleline : true},
	uhd1: {type: 2, name: `(unreal) Hfact1: Attack 1 - Damage Factor - Medium`, singleline : true},
	uhd2: {type: 2, name: `(unreal) Hfact2: Attack 2 - Damage Factor - Medium`, singleline : true},
	uisz: {type: 2, name: `(unreal) impactSwimZ: Projectile Impact - Z (Swimming)`, singleline : true},
	uimz: {type: 2, name: `(unreal) impactZ: Projectile Impact - Z`, singleline : true},
	ulsz: {type: 2, name: `(unreal) launchSwimZ: Projectile Launch - Z (Swimming)`, singleline : true},
	ulpx: {type: 2, name: `(unreal) launchX: Projectile Launch - X`, singleline : true},
	ulpy: {type: 2, name: `(unreal) launchY: Projectile Launch - Y`, singleline : true},
	ulpz: {type: 2, name: `(unreal) launchZ: Projectile Launch - Z`, singleline : true},
	uamn: {type: 0, name: `(int) minRange: Minimum Attack Range`, singleline : true},
	ua1q: {type: 0, name: `(int) Qarea1: Attack 1 - Area of Effect (Small Damage)`, singleline : true},
	ua2q: {type: 0, name: `(int) Qarea2: Attack 2 - Area of Effect (Small Damage)`, singleline : true},
	uqd1: {type: 2, name: `(unreal) Qfact1: Attack 1 - Damage Factor - Small`, singleline : true},
	uqd2: {type: 2, name: `(unreal) Qfact2: Attack 2 - Damage Factor - Small`, singleline : true},
	ua1r: {type: 0, name: `(int) rangeN1: Attack 1 - Range`, singleline : true},
	ua2r: {type: 0, name: `(int) rangeN2: Attack 2 - Range`, singleline : true},
	urb1: {type: 2, name: `(unreal) RngBuff1: Attack 1 - Range Motion Buffer`, singleline : true},
	urb2: {type: 2, name: `(unreal) RngBuff2: Attack 2 - Range Motion Buffer`, singleline : true},
	uwu1: {type: 0, name: `(bool) showUI1: Attack 1 - Show UI`, singleline : true},
	uwu2: {type: 0, name: `(bool) showUI2: Attack 2 - Show UI`, singleline : true},
	ua1s: {type: 0, name: `(int) sides1: Attack 1 - Damage Sides per Die`, singleline : true},
	ua2s: {type: 0, name: `(int) sides2: Attack 2 - Damage Sides per Die`, singleline : true},
	usd1: {type: 2, name: `(unreal) spillDist1: Attack 1 - Damage Spill Distance`, singleline : true},
	usd2: {type: 2, name: `(unreal) spillDist2: Attack 2 - Damage Spill Distance`, singleline : true},
	usr1: {type: 2, name: `(unreal) spillRadius1: Attack 1 - Damage Spill Radius`, singleline : true},
	usr2: {type: 2, name: `(unreal) spillRadius2: Attack 2 - Damage Spill Radius`, singleline : true},
	ua1p: {type: 3, name: `(targetList) splashTargs1: Attack 1 - Area of Effect Targets`, singleline : true},
	ua2p: {type: 3, name: `(targetList) splashTargs2: Attack 2 - Area of Effect Targets`, singleline : true},
	utc1: {type: 0, name: `(int) targCount1: Attack 1 - Maximum Number of Targets`, singleline : true},
	utc2: {type: 0, name: `(int) targCount2: Attack 2 - Maximum Number of Targets`, singleline : true},
	ua1g: {type: 3, name: `(targetList) targs1: Attack 1 - Targets Allowed`, singleline : true},
	ua2g: {type: 3, name: `(targetList) targs2: Attack 2 - Targets Allowed`, singleline : true},
	uaen: {type: 0, name: `(attackBits) weapsOn: Attacks Enabled`, singleline : true},
	ua1w: {type: 3, name: `(weaponType) weapTp1: Attack 1 - Weapon Type`, singleline : true},
	ua2w: {type: 3, name: `(weaponType) weapTp2: Attack 2 - Weapon Type`, singleline : true},
	ucs1: {type: 3, name: `(combatSound) weapType1: Attack 1 - Weapon Sound`, singleline : true},
	ucs2: {type: 3, name: `(combatSound) weapType2: Attack 2 - Weapon Sound`, singleline : true},
	uabs: {type: 3, name: `(abilitySkinList) abilSkinList: Normal Skin`, singleline : true},
	uhas: {type: 3, name: `(abilitySkinList) heroAbilSkinList: Hero Skin`, singleline : true},

};
export default map;