/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
	dnam: {type: 3, name: `(string) Name: Name`},
	dcat: {type: 3, name: `(doodadCategory) category: Category`, singleline : true},
	dtil: {type: 3, name: `(tilesetList) tilesets: Tilesets`, singleline : true},
	dtsp: {type: 0, name: `(bool) tilesetSpecific: Has Tileset Specific Data`, singleline : true},
	dfil: {type: 3, name: `(model) file: Model File`, singleline : true},
	dsnd: {type: 3, name: `(soundLabel) soundLoop: Looping Sound`, singleline : true},
	dsel: {type: 2, name: `(unreal) selSize: Selection Size`, singleline : true},
	ddes: {type: 2, name: `(unreal) defScale: Default Scale`, singleline : true},
	dmis: {type: 2, name: `(unreal) minScale: Minimum Scale`, singleline : true},
	dmas: {type: 2, name: `(unreal) maxScale: Maximum Scale`, singleline : true},
	dcpr: {type: 0, name: `(bool) canPlaceRandScale: Can Place Random Scale`, singleline : true},
	duch: {type: 0, name: `(bool) useClickHelper: Use Click Helper`, singleline : true},
	dimc: {type: 0, name: `(bool) ignoreModelClick: Ignore Model Clicks`, singleline : true},
	dmap: {type: 2, name: `(unreal) maxPitch: Maximum Pitch Angle (degrees)`, singleline : true},
	dmar: {type: 2, name: `(unreal) maxRoll: Max Roll Angle (degrees)`, singleline : true},
	dvis: {type: 2, name: `(unreal) visRadius: Visibility Radius`, singleline : true},
	dwlk: {type: 0, name: `(bool) walkable: Walkable`, singleline : true},
	dvar: {type: 0, name: `(int) numVar: Variations`, singleline : true},
	donc: {type: 0, name: `(bool) onCliffs: Placeable on Cliffs`, singleline : true},
	donw: {type: 0, name: `(bool) onWater: Placeable on Water`, singleline : true},
	dflt: {type: 0, name: `(bool) floats: Floats`, singleline : true},
	dshd: {type: 0, name: `(bool) shadow: Has a Shadow`, singleline : true},
	dshf: {type: 0, name: `(bool) showInFog: Show in Fog`, singleline : true},
	danf: {type: 0, name: `(bool) animInFog: Animate in Fog`, singleline : true},
	dfxr: {type: 2, name: `(unreal) fixedRot: Fixed Rotation`, singleline : true},
	dptx: {type: 3, name: `(pathingTexture) pathTex: Pathing Texture`, singleline : true},
	dsmm: {type: 0, name: `(bool) showInMM: Minimap - Show`, singleline : true},
	dumc: {type: 0, name: `(bool) useMMColor: Minimap - Use Custom Color`, singleline : true},
	dmmr: {type: 0, name: `(int) MMRed: Minimap Color 1 (Red)`, singleline : true},
	dmmg: {type: 0, name: `(int) MMGreen: Minimap Color 2 (Green)`, singleline : true},
	dmmb: {type: 0, name: `(int) MMBlue: Minimap Color 3 (Blue)`, singleline : true},
	dvr1: {type: 0, name: `(int) vertR [multilevel]: Tinting Color 1 (Red)`, level : true, singleline : true},
	dvg1: {type: 0, name: `(int) vertG [multilevel]: Tinting Color 2 (Green)`, level : true, singleline : true},
	dvb1: {type: 0, name: `(int) vertB [multilevel]: Tinting Color 3 (Blue)`, level : true, singleline : true},
	dusr: {type: 0, name: `(bool) UserList: On User-Specified List`, singleline : true},

};
export default map;