[Settings]
version = 3 # binary format version

[ANcl] # 1095656300 0x414e636c
# (bool) MissileHoming : Missile Homing Enabled
amho = 1
# (int) Missilespeed : Missile Speed
amsp = 2
# (bool) hero : Hero Ability
aher = 0
# (bool) item : Item Ability
aite = 1
# (int) levels : Levels
alev = 4
# (int) priority : Priority for Spell Steal
apri = 1
# (unitRace) race : Race
arac = "commoner"
# (bool) checkDep : Check Dependencies
achd = 0
# (techList) Requires : Requirements
areq = "hpea"
# (intList) Requiresamount : Requirements - Levels
arqa = "1"
# (orderString) Orderon : Order String - Activate
aoro = "absorb"
# (orderString) Orderoff : Order String - Deactivate
aorf = "acolyteharvest"
# (orderString) Unorder : Order String - Turn Off
aoru = "antimagicshell"
# (orderString) Order : Order String - Use/Turn On
aord = "corrosivebreath"
# (unreal) Data [multilevel]: Art Duration
Ncl4 = [
[], # use default value
0.88,
0.88,
0.88
]
# (orderString) Data [multilevel]: Base Order ID
Ncl6 = [
[], # use default value
"cloudoffog",
"cloudoffog",
"cloudoffog"
]
# (bool) Data [multilevel]: Disable Other Abilities
Ncl5 = [
0,
0,
0,
0
]
# (unreal) Data [multilevel]: Follow Through Time
Ncl1 = [
[], # use default value
179.9,
179.9,
179.9
]
# (channelFlags) Data [multilevel]: Options
Ncl3 = [
27,
11,
1,
1
]
# (channelType) Data [multilevel]: Target Type
Ncl2 = [
[], # use default value
1,
1,
1
]
# (unreal) Area [multilevel]: Area of Effect
aare = [
200,
200,
200,
200
]
# (buffList) BuffID [multilevel]: Buffs
abuf = [
[], # use default value
"BUad",
"BUad",
"BUad"
]
# (unreal) Rng [multilevel]: Cast Range
aran = [
[], # use default value
500.1,
500.1,
500.1
]
# (unreal) Cast [multilevel]: Casting Time
acas = [
[], # use default value
3,
3,
3
]
# (unreal) Cool [multilevel]: Cooldown
acdn = [
[], # use default value
3,
3,
3
]
# (unreal) HeroDur [multilevel]: Duration - Hero
ahdu = [
[], # use default value
4,
4,
4
]
# (unreal) Dur [multilevel]: Duration - Normal
adur = [
[], # use default value
4,
4,
4
]
# (effectList) EfctID [multilevel]: Effects
aeff = [
[], # use default value
"Xfom",
"Xfom",
"Xfom"
]
# (int) Cost [multilevel]: Mana Cost
amcs = [
[], # use default value
2,
4,
5
]
# (targetList) targs [multilevel]: Targets Allowed
atar = [
[], # use default value
"air",
"enemies,friend",
"structure,sapper,terrain"
]
