[Settings]
version = 3 # binary format version

[Sch4] # 1399023668 0x53636834
# CARGO_CAPACITY
Car1 = [
1,
6
]
Car1Data = [
1,
1
]
# MISSILE_SPEED
amsp = 2
# HOMING (boolean)
amho = 1
abufType = "string"
abuf = [
"""Bmlc""",
"""Bplg"""
]
# AREA_OF_EFFECT
aare = [
300,
8
]
# CAST_RANGE
aran = [
1,
1
]
# CASTING_TIME
acas = [
1,
3
]
# COOLDOWN
acdn = [
1,
5
]
# DURATION_HERO
ahdu = [
1,
5
]
# DURATION_NORMAL
adur = [
1,
5
]
aeffType = "string"
aeff = [
"""Xfos""",
"""XNhs"""
]
# ITEM_ABILITY (boolean)
aite = 1
# HERO_ABILITY (boolean)
aher = 1
# MANA_COST
amcs = [
1,
5
]
# LEVELS
alev = 2
# TARGETS_ALLOWED
atar = [
"""friend,ground,invulnerable,neutral,vulnerable""",
"""notself"""
]
# PRIORITY
apri = 2
aracType = "string"
arac = """demon"""
# CHECK_DEPENDENCIES (boolean)
achd = 0
areqType = "string"
areq = """hmpr"""
arqaType = "string"
arqa = """1"""
aoroType = "string"
aoro = """acidbomb"""
aorfType = "string"
aorf = """acidbomb"""
aoruType = "string"
aoru = """acolyteharvest"""
aordType = "string"
aord = """acolyteharvest"""

[S000] # 1395666992 0x53303030
parent = "Sch4" # 1399023668 0x53636834
# CARGO_CAPACITY
Car1 = [
1,
6
]
Car1Data = [
1,
1
]
# MISSILE_SPEED
amsp = 2
# HOMING (boolean)
amho = 1
abufType = "string"
abuf = [
"""Bmlc""",
"""Bplg"""
]
# AREA_OF_EFFECT
aare = [
300,
8
]
# CAST_RANGE
aran = [
1,
1
]
# CASTING_TIME
acas = [
1,
3
]
# COOLDOWN
acdn = [
1,
5
]
# DURATION_HERO
ahdu = [
1,
5
]
# DURATION_NORMAL
adur = [
1,
5
]
aeffType = "string"
aeff = [
"""Xfos""",
"""XNhs"""
]
# ITEM_ABILITY (boolean)
aite = 1
# HERO_ABILITY (boolean)
aher = 1
# MANA_COST
amcs = [
1,
5
]
# LEVELS
alev = 2
# TARGETS_ALLOWED
atar = [
"""friend,ground,invulnerable,neutral,vulnerable""",
"""notself"""
]
# PRIORITY
apri = 2
aracType = "string"
arac = """demon"""
# CHECK_DEPENDENCIES (boolean)
achd = 0
areqType = "string"
areq = """hmpr"""
arqaType = "string"
arqa = """1"""
aoroType = "string"
aoro = """acidbomb"""
aorfType = "string"
aorf = """acidbomb"""
aoruType = "string"
aoru = """acolyteharvest"""
aordType = "string"
aord = """acolyteharvest"""
