[Settings]
version = 3 # binary format version

[ANcl] # 1095656300 0x414e636c
# HOMING, boolean
amho = 1
# MISSILE_SPEED, integer
amsp = 2
# HERO_ABILITY, boolean
aher = 0
# ITEM_ABILITY, boolean
aite = 1
# LEVELS, integer
alev = 4
# PRIORITY, integer
apri = 1
# _UNDEFINED, string
arac = "commoner"
# CHECK_DEPENDENCIES, boolean
achd = 0
# _UNDEFINED, string
areq = "hpea"
# _UNDEFINED, string
arqa = "1"
# _UNDEFINED, string
aoro = "absorb"
# _UNDEFINED, string
aorf = "acolyteharvest"
# _UNDEFINED, string
aoru = "antimagicshell"
# _UNDEFINED, string
aord = "corrosivebreath"
# ART_DURATION, real, multilevel
Ncl4 = [
[], # use default value
0.88,
0.88,
0.88
]
# _UNDEFINED, string, multilevel
Ncl6 = [
[], # use default value
"cloudoffog",
"cloudoffog",
"cloudoffog"
]
# DISABLE_OTHER_ABILITIES, boolean, multilevel
Ncl5 = [
0,
0,
0,
0
]
Ncl5Data = [
5,
5,
5,
5
]
# FOLLOW_THROUGH_TIME, real, multilevel
Ncl1 = [
[], # use default value
179.9,
179.9,
179.9
]
# OPTIONS, integer, multilevel
Ncl3 = [
27,
11,
1,
1
]
Ncl3Data = [
3,
3,
3,
3
]
# TARGET_TYPE, integer, multilevel
Ncl2 = [
[], # use default value
1,
1,
1
]
# AREA_OF_EFFECT, real, multilevel
aare = [
200,
200,
200,
200
]
# _UNDEFINED, string, multilevel
abuf = [
[], # use default value
"BUad",
"BUad",
"BUad"
]
# CAST_RANGE, real, multilevel
aran = [
[], # use default value
500.1,
500.1,
500.1
]
# CASTING_TIME, real, multilevel
acas = [
[], # use default value
3,
3,
3
]
# COOLDOWN, real, multilevel
acdn = [
[], # use default value
3,
3,
3
]
# DURATION_HERO, real, multilevel
ahdu = [
[], # use default value
4,
4,
4
]
# DURATION_NORMAL, real, multilevel
adur = [
[], # use default value
4,
4,
4
]
# _UNDEFINED, string, multilevel
aeff = [
[], # use default value
"Xfom",
"Xfom",
"Xfom"
]
# MANA_COST, integer, multilevel
amcs = [
[], # use default value
2,
4,
5
]
# _UNDEFINED, string, multilevel
atar = [
[], # use default value
"air",
"enemies,friend",
"structure,sapper,terrain"
]
