/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
	gnam: {type: 3, name: `(string) Name [multilevel]: Name`, level : true},
	gnsf: {type: 3, name: `(string) EditorSuffix [multilevel]: Editor Suffix`, level : true},
	grac: {type: 3, name: `(unitRace) race: Race`, singleline : true},
	gtp1: {type: 3, name: `(string) Tip [multilevel]: Tooltip`, level : true},
	gub1: {type: 3, name: `(string) Ubertip [multilevel]: Tooltip - Extended`, level : true},
	ghk1: {type: 3, name: `(char) Hotkey [multilevel]: Hotkey`, level : true, singleline : true},
	gbpx: {type: 0, name: `(int) Buttonpos: Button Position (X)`, singleline : true},
	gbpy: {type: 0, name: `(int) Buttonpos: Button Position (Y)`, singleline : true},
	gar1: {type: 3, name: `(icon) Art [multilevel]: Icon`, level : true, singleline : true},
	gcls: {type: 3, name: `(upgradeClass) class: Class`, singleline : true},
	glvl: {type: 0, name: `(int) maxlevel: Levels`, singleline : true},
	gglb: {type: 0, name: `(int) goldbase: Gold Base`, singleline : true},
	gglm: {type: 0, name: `(int) goldmod: Gold Increment`, singleline : true},
	glmb: {type: 0, name: `(int) lumberbase: Lumber Base`, singleline : true},
	glmm: {type: 0, name: `(int) lumbermod: Lumber Increment`, singleline : true},
	gtib: {type: 0, name: `(int) timebase: Time Base`, singleline : true},
	gtim: {type: 0, name: `(int) timemod: Time Increment`, singleline : true},
	gef1: {type: 3, name: `(upgradeEffect) effect1: Effect 1`, singleline : true},
	gba1: {type: 2, name: `(unreal) base1: Effect 1 - %s`, singleline : true},
	gmo1: {type: 2, name: `(unreal) mod1: Effect 1 - %s`, singleline : true},
	gco1: {type: 3, name: `(string) code1: Effect 1 - %s`},
	gef2: {type: 3, name: `(upgradeEffect) effect2: Effect 2`, singleline : true},
	gba2: {type: 2, name: `(unreal) base2: Effect 2 - %s`, singleline : true},
	gmo2: {type: 2, name: `(unreal) mod2: Effect 2 - %s`, singleline : true},
	gco2: {type: 3, name: `(string) code2: Effect 2 - %s`},
	gef3: {type: 3, name: `(upgradeEffect) effect3: Effect 3`, singleline : true},
	gba3: {type: 2, name: `(unreal) base3: Effect 3 - %s`, singleline : true},
	gmo3: {type: 2, name: `(unreal) mod3: Effect 3 - %s`, singleline : true},
	gco3: {type: 3, name: `(string) code3: Effect 3 - %s`},
	gef4: {type: 3, name: `(upgradeEffect) effect4: Effect 4`, singleline : true},
	gba4: {type: 2, name: `(unreal) base4: Effect 4 - %s`, singleline : true},
	gmo4: {type: 2, name: `(unreal) mod4: Effect 4 - %s`, singleline : true},
	gco4: {type: 3, name: `(string) code4: Effect 4 - %s`},
	ginh: {type: 0, name: `(bool) inherit: Transfer with Unit Ownership`, singleline : true},
	greq: {type: 3, name: `(techList) Requires [multilevel]: Requirements`, level : true, singleline : true},
	grqc: {type: 3, name: `(intList) Requiresamount [multilevel]: Requirements - Levels`, level : true, singleline : true},
	glob: {type: 0, name: `(bool) global: Applies to All Units`, singleline : true},

};
export default map;