/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
	anam: {type: 3, data : 0, name: `(string) Name: Name`},
	ansf: {type: 3, data : 0, name: `(string) EditorSuffix: Editor Suffix`},
	aher: {type: 0, data : 0, name: `(bool) hero: Hero Ability`, singleline : true},
	aite: {type: 0, data : 0, name: `(bool) item: Item Ability`, singleline : true},
	arac: {type: 3, data : 0, name: `(unitRace) race: Race`, singleline : true},
	abpx: {type: 0, data : 0, name: `(int) Buttonpos: Button Position - Normal (X)`, singleline : true},
	abpy: {type: 0, data : 0, name: `(int) Buttonpos: Button Position - Normal (Y)`, singleline : true},
	aubx: {type: 0, data : 0, name: `(int) UnButtonpos: Button Position - Turn Off (X)`, singleline : true},
	auby: {type: 0, data : 0, name: `(int) UnButtonpos: Button Position - Turn Off (Y)`, singleline : true},
	arpx: {type: 0, data : 0, name: `(int) Researchbuttonpos: Button Position - Research (X)`, singleline : true},
	arpy: {type: 0, data : 0, name: `(int) Researchbuttonpos: Button Position - Research (Y)`, singleline : true},
	aart: {type: 3, data : 0, name: `(icon) Art: Icon - Normal`, singleline : true},
	auar: {type: 3, data : 0, name: `(icon) Unart: Icon - Turn Off`, singleline : true},
	arar: {type: 3, data : 0, name: `(icon) ResearchArt: Icon - Research`, singleline : true},
	acat: {type: 3, data : 0, name: `(modelList) CasterArt: Caster`, singleline : true},
	atat: {type: 3, data : 0, name: `(modelList) TargetArt: Target`, singleline : true},
	asat: {type: 3, data : 0, name: `(modelList) SpecialArt: Special`, singleline : true},
	aeat: {type: 3, data : 0, name: `(modelList) EffectArt: Effect`, singleline : true},
	aaea: {type: 3, data : 0, name: `(modelList) Areaeffectart: Area Effect`, singleline : true},
	alig: {type: 3, data : 0, name: `(lightningList) LightningEffect: Lightning Effects`, singleline : true},
	amat: {type: 3, data : 0, name: `(modelList) Missileart: Missile Art`, singleline : true},
	amsp: {type: 0, data : 0, name: `(int) Missilespeed: Missile Speed`, singleline : true},
	amac: {type: 2, data : 0, name: `(unreal) Missilearc: Missile Arc`, singleline : true},
	amho: {type: 0, data : 0, name: `(bool) MissileHoming: Missile Homing Enabled`, singleline : true},
	atac: {type: 0, data : 0, name: `(int) Targetattachcount: Target Attachments`, singleline : true},
	ata0: {type: 3, data : 0, name: `(stringList) Targetattach: Target Attachment Point 1`, singleline : true},
	ata1: {type: 3, data : 0, name: `(stringList) Targetattach1: Target Attachment Point 2`, singleline : true},
	ata2: {type: 3, data : 0, name: `(stringList) Targetattach2: Target Attachment Point 3`, singleline : true},
	ata3: {type: 3, data : 0, name: `(stringList) Targetattach3: Target Attachment Point 4`, singleline : true},
	ata4: {type: 3, data : 0, name: `(stringList) Targetattach4: Target Attachment Point 5`, singleline : true},
	ata5: {type: 3, data : 0, name: `(stringList) Targetattach5: Target Attachment Point 6`, singleline : true},
	acac: {type: 0, data : 0, name: `(int) Casterattachcount: Caster Attachments`, singleline : true},
	acap: {type: 3, data : 0, name: `(stringList) Casterattach: Caster Attachment Point 1`, singleline : true},
	aca1: {type: 3, data : 0, name: `(stringList) Casterattach1: Caster Attachment Point 2`, singleline : true},
	aspt: {type: 3, data : 0, name: `(stringList) Specialattach: Special Attachment Point`, singleline : true},
	aani: {type: 3, data : 0, name: `(stringList) Animnames: Animation Names`, singleline : true},
	atp1: {type: 3, data : 0, name: `(string) Tip [multilevel]: Tooltip - Normal`, level : true},
	aut1: {type: 3, data : 0, name: `(string) Untip [multilevel]: Tooltip - Turn Off`, level : true},
	aub1: {type: 3, data : 0, name: `(string) Ubertip [multilevel]: Tooltip - Normal - Extended`, level : true},
	auu1: {type: 3, data : 0, name: `(string) Unubertip [multilevel]: Tooltip - Turn Off - Extended`, level : true},
	aret: {type: 3, data : 0, name: `(string) Researchtip: Tooltip - Learn`},
	arut: {type: 3, data : 0, name: `(string) Researchubertip: Tooltip - Learn - Extended`},
	arhk: {type: 3, data : 0, name: `(char) Researchhotkey: Hotkey - Learn`, singleline : true},
	ahky: {type: 3, data : 0, name: `(char) Hotkey: Hotkey - Normal`, singleline : true},
	auhk: {type: 3, data : 0, name: `(char) Unhotkey: Hotkey - Turn Off`, singleline : true},
	areq: {type: 3, data : 0, name: `(techList) Requires: Requirements`, singleline : true},
	arqa: {type: 3, data : 0, name: `(intList) Requiresamount: Requirements - Levels`, singleline : true},
	achd: {type: 0, data : 0, name: `(bool) checkDep: Check Dependencies`, singleline : true},
	apri: {type: 0, data : 0, name: `(int) priority: Priority for Spell Steal`, singleline : true},
	aord: {type: 3, data : 0, name: `(orderString) Order: Order String - Use/Turn On`, singleline : true},
	aoru: {type: 3, data : 0, name: `(orderString) Unorder: Order String - Turn Off`, singleline : true},
	aoro: {type: 3, data : 0, name: `(orderString) Orderon: Order String - Activate`, singleline : true},
	aorf: {type: 3, data : 0, name: `(orderString) Orderoff: Order String - Deactivate`, singleline : true},
	aefs: {type: 3, data : 0, name: `(soundLabel) Effectsound: Effect Sound`, singleline : true},
	aefl: {type: 3, data : 0, name: `(soundLabel) Effectsoundlooped: Effect Sound (Looping)`, singleline : true},
	alev: {type: 0, data : 0, name: `(int) levels: Levels`, singleline : true},
	arlv: {type: 0, data : 0, name: `(int) reqLevel: Required Level`, singleline : true},
	alsk: {type: 0, data : 0, name: `(int) levelSkip: Level Skip Requirement`, singleline : true},
	atar: {type: 3, data : 0, name: `(targetList) targs [multilevel]: Targets Allowed`, level : true, singleline : true},
	acas: {type: 2, data : 0, name: `(unreal) Cast [multilevel]: Casting Time`, level : true, singleline : true},
	adur: {type: 2, data : 0, name: `(unreal) Dur [multilevel]: Duration - Normal`, level : true, singleline : true},
	ahdu: {type: 2, data : 0, name: `(unreal) HeroDur [multilevel]: Duration - Hero`, level : true, singleline : true},
	acdn: {type: 2, data : 0, name: `(unreal) Cool [multilevel]: Cooldown`, level : true, singleline : true},
	amcs: {type: 0, data : 0, name: `(int) Cost [multilevel]: Mana Cost`, level : true, singleline : true},
	aare: {type: 2, data : 0, name: `(unreal) Area [multilevel]: Area of Effect`, level : true, singleline : true},
	aran: {type: 2, data : 0, name: `(unreal) Rng [multilevel]: Cast Range`, level : true, singleline : true},
	abuf: {type: 3, data : 0, name: `(buffList) BuffID [multilevel]: Buffs`, level : true, singleline : true},
	aeff: {type: 3, data : 0, name: `(effectList) EfctID [multilevel]: Effects`, level : true, singleline : true},
	Hbz1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Waves`, level : true, singleline : true},
	Hbz2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Hbz3: {type: 0, data : 3, name: `(int) Data [multilevel]: Number of Shards`, level : true, singleline : true},
	Hbz4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Building Reduction`, level : true, singleline : true},
	Hbz5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Hbz6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Maximum Damage per Wave`, level : true, singleline : true},
	Hab1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Regeneration Increase`, level : true, singleline : true},
	Hab2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Percent Bonus`, level : true, singleline : true},
	Hmt1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Units Teleported`, level : true, singleline : true},
	Hmt2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Casting Delay`, level : true, singleline : true},
	Hmt3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Use Teleport Clustering`, level : true, singleline : true},
	Hwe1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	Hwe2: {type: 0, data : 1, name: `(int) Data [multilevel]: Summoned Unit Count`, level : true, singleline : true},
	Oww1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Oww2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Ocr1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Critical Strike`, level : true, singleline : true},
	Ocr2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Multiplier`, level : true, singleline : true},
	Ocr3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Ocr4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Chance to Evade`, level : true, singleline : true},
	Ocr5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Never Miss`, level : true, singleline : true},
	Ocr6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Exclude Item Damage`, level : true, singleline : true},
	Omi1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Images`, level : true, singleline : true},
	Omi2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Dealt (%)`, level : true, singleline : true},
	Omi3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Taken (%)`, level : true, singleline : true},
	Omi4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Animation Delay`, level : true, singleline : true},
	Owk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Transition Time`, level : true, singleline : true},
	Owk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Increase (%)`, level : true, singleline : true},
	Owk3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Backstab Damage`, level : true, singleline : true},
	Owk4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Backstab Damage`, level : true, singleline : true},
	Owk5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Start Cooldown when Decloak`, level : true, singleline : true},
	Uan1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Corpses Raised`, level : true, singleline : true},
	Uan3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Inherit Upgrades`, level : true, singleline : true},
	Udc1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Amount Healed/Damaged`, level : true, singleline : true},
	Udp1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Converted to Mana`, level : true, singleline : true},
	Udp2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Life Converted to Life`, level : true, singleline : true},
	Udp3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Mana Conversion As Percent`, level : true, singleline : true},
	Udp4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Life Conversion As Percent`, level : true, singleline : true},
	Udp5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Leave Target Alive`, level : true, singleline : true},
	Uau1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Increase (%)`, level : true, singleline : true},
	Uau2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Life Regeneration Increase (%)`, level : true, singleline : true},
	Uau3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Percent Bonus`, level : true, singleline : true},
	Eev1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Evade`, level : true, singleline : true},
	Eim1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage per Interval`, level : true, singleline : true},
	Eim2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Drained per Second`, level : true, singleline : true},
	Eim3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Buffer Mana Required`, level : true, singleline : true},
	Emb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Max Mana Drained`, level : true, singleline : true},
	Emb2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Bolt Delay`, level : true, singleline : true},
	Emb3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Bolt Lifetime`, level : true, singleline : true},
	Eme1: {type: 0, data : 1, name: `(unitCode) Data [multilevel]: Normal Form Unit`, level : true, singleline : true},
	Eme2: {type: 0, data : 2, name: `(morphFlags) Data [multilevel]: Morphing Flags`, level : true, singleline : true},
	Eme3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Altitude Adjustment Duration`, level : true, singleline : true},
	Eme4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Landing Delay Time`, level : true, singleline : true},
	Eme5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Alternate Form Hit Point Bonus`, level : true, singleline : true},
	Ncr5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Move Speed Bonus (Info Panel Only)`, level : true, singleline : true},
	Ncr6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Attack Speed Bonus (Info Panel Only)`, level : true, singleline : true},
	Nrg5: {type: 0, data : 5, name: `(int) Data [multilevel]: Strength Bonus`, level : true, singleline : true},
	Nrg6: {type: 0, data : 6, name: `(int) Data [multilevel]: Defense Bonus`, level : true, singleline : true},
	ave5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Life Regeneration Rate (per second)`, level : true, singleline : true},
	Emeu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Alternate Form Unit`, level : true, singleline : true},
	Usl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Stun Duration`, level : true, singleline : true},
	Uav1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Damage Stolen (%)`, level : true, singleline : true},
	Ucs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Ucs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Max Damage`, level : true, singleline : true},
	Ucs3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Distance`, level : true, singleline : true},
	Ucs4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Final Area`, level : true, singleline : true},
	Uin1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Uin2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Duration`, level : true, singleline : true},
	Uin3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Impact Delay`, level : true, singleline : true},
	Uin4: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit`, level : true, singleline : true},
	Ocl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage per Target`, level : true, singleline : true},
	Ocl2: {type: 0, data : 2, name: `(int) Data [multilevel]: Number of Targets Hit`, level : true, singleline : true},
	Ocl3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Reduction per Target`, level : true, singleline : true},
	Oeq1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Effect Delay`, level : true, singleline : true},
	Oeq2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage per Second to Buildings`, level : true, singleline : true},
	Oeq3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Units Slowed (%)`, level : true, singleline : true},
	Oeq4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Final Area`, level : true, singleline : true},
	Ofs1: {type: 0, data : 1, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Osf1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit`, level : true, singleline : true},
	Osf2: {type: 0, data : 2, name: `(int) Data [multilevel]: Number of Summoned Units`, level : true, singleline : true},
	Eer1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Efn1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Summoned Units`, level : true, singleline : true},
	Efnu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	Eah1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Dealt to Attackers`, level : true, singleline : true},
	Eah2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Damage is Percent Received`, level : true, singleline : true},
	Etq1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Healed`, level : true, singleline : true},
	Etq2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Heal Interval`, level : true, singleline : true},
	Etq3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Building Reduction`, level : true, singleline : true},
	Etq4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Initial Immunity Duration`, level : true, singleline : true},
	Udd1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Max Life Drained per Second (%)`, level : true, singleline : true},
	Udd2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Building Reduction`, level : true, singleline : true},
	Ufa1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Armor Duration`, level : true, singleline : true},
	Ufa2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Armor Bonus`, level : true, singleline : true},
	Ufn1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Area of Effect Damage`, level : true, singleline : true},
	Ufn2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Specific Target Damage`, level : true, singleline : true},
	Ufn5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Максимальный урон`, level : true, singleline : true},
	Hfa1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Esf1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Dealt`, level : true, singleline : true},
	Esf2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Interval`, level : true, singleline : true},
	Esf3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Building Reduction`, level : true, singleline : true},
	Ear1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus (%)`, level : true, singleline : true},
	Ear2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Melee Bonus`, level : true, singleline : true},
	Ear3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Ranged Bonus`, level : true, singleline : true},
	Ear4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Flat Bonus`, level : true, singleline : true},
	Hav1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Defense Bonus`, level : true, singleline : true},
	Hav2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Hit Point Bonus`, level : true, singleline : true},
	Hav3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Hav4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Hbh1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Bash`, level : true, singleline : true},
	Hbh2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Multiplier`, level : true, singleline : true},
	Hbh3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Hbh4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Chance to Miss`, level : true, singleline : true},
	Hbh5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Never Miss`, level : true, singleline : true},
	Htb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Htc1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: AOE Damage`, level : true, singleline : true},
	Htc2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Specific Target Damage`, level : true, singleline : true},
	Htc3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Movement Speed Reduction (%)`, level : true, singleline : true},
	Htc4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Attack Speed Reduction (%)`, level : true, singleline : true},
	Htc5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Максимальный урон`, level : true, singleline : true},
	Had1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Armor Bonus`, level : true, singleline : true},
	Had2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Percent Bonus`, level : true, singleline : true},
	Hds1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Can Deactivate`, level : true, singleline : true},
	Hhb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Amount Healed/Damaged`, level : true, singleline : true},
	Hre1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Corpses Raised`, level : true, singleline : true},
	Hre2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Raised Units Are Invulnerable`, level : true, singleline : true},
	Hca1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Extra Damage`, level : true, singleline : true},
	Hca2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Hca3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Hca4: {type: 0, data : 4, name: `(stackFlags) Data [multilevel]: Stack Flags`, level : true, singleline : true},
	Oae1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Increase (%)`, level : true, singleline : true},
	Oae2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Increase (%)`, level : true, singleline : true},
	Ore1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Reincarnation Delay`, level : true, singleline : true},
	Osh1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Osh2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Maximum Damage`, level : true, singleline : true},
	Osh3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Distance`, level : true, singleline : true},
	Osh4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Final Area`, level : true, singleline : true},
	Nfd1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Graphic Delay`, level : true, singleline : true},
	Nfd2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Graphic Duration`, level : true, singleline : true},
	Nfd3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Ndp1: {type: 3, data : 1, name: `(unitList) Data [multilevel]: Spawned Units`, level : true, singleline : true},
	Ndp2: {type: 0, data : 2, name: `(int) Data [multilevel]: Minimum Number of Units`, level : true, singleline : true},
	Ndp3: {type: 0, data : 3, name: `(int) Data [multilevel]: Maximum Number of Units`, level : true, singleline : true},
	Nrc1: {type: 3, data : 1, name: `(abilCode) Data [multilevel]: Ability for Unit Creation`, level : true, singleline : true},
	Nrc2: {type: 0, data : 2, name: `(int) Data [multilevel]: Number of Units Created`, level : true, singleline : true},
	Ams1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	Ams2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Ams3: {type: 0, data : 3, name: `(int) Data [multilevel]: Shield Life`, level : true, singleline : true},
	Ams4: {type: 0, data : 4, name: `(int) Data [multilevel]: Mana Loss`, level : true, singleline : true},
	Apl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Aura Duration`, level : true, singleline : true},
	Apl2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Apl3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Duration of Plague Ward`, level : true, singleline : true},
	Aplu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Plague Ward Unit Type`, level : true, singleline : true},
	Oar1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Amount of Hit Points Regenerated`, level : true, singleline : true},
	Oar2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Percentage`, level : true, singleline : true},
	Akb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Damage Increase`, level : true, singleline : true},
	Adm1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Loss`, level : true, singleline : true},
	Adm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	Btl1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Allowed Unit Type`, level : true, singleline : true},
	Btl2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Summon Busy Units`, level : true, singleline : true},
	Bli1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Expansion Amount`, level : true, singleline : true},
	Bli2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Creates Blight`, level : true, singleline : true},
	Bgm1: {type: 0, data : 1, name: `(int) Data [multilevel]: Gold per Interval`, level : true, singleline : true},
	Bgm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Interval Duration`, level : true, singleline : true},
	Bgm3: {type: 0, data : 3, name: `(int) Data [multilevel]: Max Number of Miners`, level : true, singleline : true},
	Bgm4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Radius of Mining Ring`, level : true, singleline : true},
	Blo1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Speed Increase (%)`, level : true, singleline : true},
	Blo2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Increase (%)`, level : true, singleline : true},
	Blo3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Scaling Factor`, level : true, singleline : true},
	Can1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Hit Points per Second`, level : true, singleline : true},
	Can2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Max Hit Points`, level : true, singleline : true},
	Car1: {type: 0, data : 1, name: `(int) Data [multilevel]: Cargo Capacity`, level : true, singleline : true},
	Dev2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Dev3: {type: 0, data : 3, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Chd1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Update Frequency`, level : true, singleline : true},
	Chd2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Update Frequency`, level : true, singleline : true},
	Chd3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	Cha1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: New Unit Type`, level : true, singleline : true},
	Cri1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Reduction (%)`, level : true, singleline : true},
	Cri2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Reduction (%)`, level : true, singleline : true},
	Cri3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Reduction`, level : true, singleline : true},
	Crs: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Miss`, level : true, singleline : true},
	Dda1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Full Damage Radius`, level : true, singleline : true},
	Dda2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Full Damage Amount`, level : true, singleline : true},
	Dda3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Partial Damage Radius`, level : true, singleline : true},
	Dda4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Partial Damage Amount`, level : true, singleline : true},
	Sds1: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Building Damage Factor`, level : true, singleline : true},
	Sds6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Explodes on Death`, level : true, singleline : true},
	Uco5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Max Damage`, level : true, singleline : true},
	Uco6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Move Speed Bonus`, level : true, singleline : true},
	Def1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Taken (%)`, level : true, singleline : true},
	Def2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Dealt (%)`, level : true, singleline : true},
	Def3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Def4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Def5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Def6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Chance to Deflect`, level : true, singleline : true},
	Def7: {type: 2, data : 7, name: `(unreal) Data [multilevel]: Deflect Damage Taken (Piercing)`, level : true, singleline : true},
	Def8: {type: 2, data : 8, name: `(unreal) Data [multilevel]: Deflect Damage Taken (Spells)`, level : true, singleline : true},
	Dev1: {type: 0, data : 1, name: `(int) Data [multilevel]: Max Creep Level`, level : true, singleline : true},
	Eat1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Rip Delay`, level : true, singleline : true},
	Eat2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Eat Delay`, level : true, singleline : true},
	Eat3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Ens1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Air Unit Lower Duration`, level : true, singleline : true},
	Ens2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Air Unit Height`, level : true, singleline : true},
	Ens3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Melee Attack Range`, level : true, singleline : true},
	ent1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Resulting Unit Type`, level : true, singleline : true},
	Egm1: {type: 0, data : 1, name: `(int) Data [multilevel]: Gold per Interval`, level : true, singleline : true},
	Egm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Interval Duration`, level : true, singleline : true},
	Fae1: {type: 0, data : 1, name: `(int) Data [multilevel]: Defense Reduction`, level : true, singleline : true},
	Fae2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Always Autocast`, level : true, singleline : true},
	Fla1: {type: 0, data : 1, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Fla2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Effect Delay`, level : true, singleline : true},
	Fla3: {type: 0, data : 3, name: `(int) Data [multilevel]: Flare Count`, level : true, singleline : true},
	Gld1: {type: 0, data : 1, name: `(int) Data [multilevel]: Max Gold`, level : true, singleline : true},
	Gld2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mining Duration`, level : true, singleline : true},
	Gld3: {type: 0, data : 3, name: `(int) Data [multilevel]: Mining Capacity`, level : true, singleline : true},
	Gyd1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Number of Corpses`, level : true, singleline : true},
	Gyd2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Radius of Gravestones`, level : true, singleline : true},
	Gyd3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Radius of Corpses`, level : true, singleline : true},
	Gydu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Corpse Unit Type`, level : true, singleline : true},
	Har1: {type: 0, data : 1, name: `(int) Data [multilevel]: Damage to Tree`, level : true, singleline : true},
	Har2: {type: 0, data : 2, name: `(int) Data [multilevel]: Lumber Capacity`, level : true, singleline : true},
	Har3: {type: 0, data : 3, name: `(int) Data [multilevel]: Gold Capacity`, level : true, singleline : true},
	Hea1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Inf1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Increase (%)`, level : true, singleline : true},
	Inf2: {type: 0, data : 2, name: `(int) Data [multilevel]: Defense Increase`, level : true, singleline : true},
	Inf3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Autocast Range`, level : true, singleline : true},
	Inf4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Life Regen Rate`, level : true, singleline : true},
	Lit1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Graphic Delay`, level : true, singleline : true},
	Lit2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Graphic Duration`, level : true, singleline : true},
	Lsh1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Loa1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Allowed Unit Type`, level : true, singleline : true},
	Mbt1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Gained`, level : true, singleline : true},
	Mbt2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Mbt3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Autocast Requirement`, level : true, singleline : true},
	Mbt4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Water Height`, level : true, singleline : true},
	Mbt5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Regenerate Only At Night`, level : true, singleline : true},
	Mil1: {type: 0, data : 1, name: `(unitCode) Data [multilevel]: Normal Form Unit`, level : true, singleline : true},
	Mil2: {type: 0, data : 2, name: `(unitCode) Data [multilevel]: Alternate Form Unit`, level : true, singleline : true},
	Min1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Activation Delay`, level : true, singleline : true},
	Min2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Invisibility Transition Time`, level : true, singleline : true},
	Neu1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Activation Radius`, level : true, singleline : true},
	Neu2: {type: 0, data : 2, name: `(interactionFlags) Data [multilevel]: Interaction Type`, level : true, singleline : true},
	Neu3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Show Select Unit Button`, level : true, singleline : true},
	Neu4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Show Unit Indicator`, level : true, singleline : true},
	Ndt1: {type: 0, data : 1, name: `(int) Data [multilevel]: Gold Cost`, level : true, singleline : true},
	Ndt2: {type: 0, data : 2, name: `(int) Data [multilevel]: Lumber Cost`, level : true, singleline : true},
	Ndt3: {type: 0, data : 3, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Ans5: {type: 3, data : 5, name: `(orderString) Data [multilevel]: Base Order ID`, level : true, singleline : true},
	Ans6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Charge Owning Player`, level : true, singleline : true},
	Arm1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Amount Regenerated`, level : true, singleline : true},
	Arm2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Percentage`, level : true, singleline : true},
	Poi1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Poi2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Poi3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Poi4: {type: 0, data : 4, name: `(stackFlags) Data [multilevel]: Stacking Type`, level : true, singleline : true},
	Poa1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Extra Damage`, level : true, singleline : true},
	Poa2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Poa3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Poa4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Poa5: {type: 0, data : 5, name: `(stackFlags) Data [multilevel]: Stacking Type`, level : true, singleline : true},
	Ply1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Ply2: {type: 3, data : 2, name: `(unitList) Data [multilevel]: Morph Units - Ground`, level : true, singleline : true},
	Ply3: {type: 3, data : 3, name: `(unitList) Data [multilevel]: Morph Units - Air`, level : true, singleline : true},
	Ply4: {type: 3, data : 4, name: `(unitList) Data [multilevel]: Morph Units - Amphibious`, level : true, singleline : true},
	Ply5: {type: 3, data : 5, name: `(unitList) Data [multilevel]: Morph Units - Water`, level : true, singleline : true},
	Pos1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Pos2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Amplification`, level : true, singleline : true},
	Pos3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Target Is Invulnerable`, level : true, singleline : true},
	Pos4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Target Is Magic Immune`, level : true, singleline : true},
	War1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Stomp (%)`, level : true, singleline : true},
	War2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Dealt`, level : true, singleline : true},
	War3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Full Damage Radius`, level : true, singleline : true},
	War4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Half Damage Radius`, level : true, singleline : true},
	Prg1: {type: 0, data : 1, name: `(int) Data [multilevel]: Movement Update Frequency`, level : true, singleline : true},
	Prg2: {type: 0, data : 2, name: `(int) Data [multilevel]: Attack Update Frequency`, level : true, singleline : true},
	Prg3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	Prg4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Unit Pause Duration`, level : true, singleline : true},
	Prg5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Hero Pause Duration`, level : true, singleline : true},
	Prg6: {type: 0, data : 6, name: `(int) Data [multilevel]: Mana Loss`, level : true, singleline : true},
	Rai1: {type: 0, data : 1, name: `(int) Data [multilevel]: Units Summoned (Type One)`, level : true, singleline : true},
	Rai2: {type: 0, data : 2, name: `(int) Data [multilevel]: Units Summoned (Type Two)`, level : true, singleline : true},
	Rai3: {type: 0, data : 3, name: `(unitCode) Data [multilevel]: Unit Type One`, level : true, singleline : true},
	Rai4: {type: 0, data : 4, name: `(unitCode) Data [multilevel]: Unit Type Two`, level : true, singleline : true},
	Raiu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Unit Type For Limit Check`, level : true, singleline : true},
	Ucb5: {type: 0, data : 5, name: `(int) Data [multilevel]: Max Units Summoned`, level : true, singleline : true},
	Ucb6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Kill On Caster Death`, level : true, singleline : true},
	Rej1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Rej2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Points Gained`, level : true, singleline : true},
	Rej3: {type: 0, data : 3, name: `(fullFlags) Data [multilevel]: Allow When Full`, level : true, singleline : true},
	Rej4: {type: 0, data : 4, name: `(bool) Data [multilevel]: No Target Required`, level : true, singleline : true},
	Rpb3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Minimum Life Required`, level : true, singleline : true},
	Rpb4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Minimum Mana Required`, level : true, singleline : true},
	Rpb5: {type: 0, data : 5, name: `(int) Data [multilevel]: Maximum Units Charged To Caster`, level : true, singleline : true},
	Rpb6: {type: 0, data : 0, name: `(int) Cast [multilevel]: Maximum Units Affected`, level : true, singleline : true},
	Rep1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Repair Cost Ratio`, level : true, singleline : true},
	Rep2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Repair Time Ratio`, level : true, singleline : true},
	Rep3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Powerbuild Cost`, level : true, singleline : true},
	Rep4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Powerbuild Rate`, level : true, singleline : true},
	Rep5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Naval Range Bonus`, level : true, singleline : true},
	Rtn1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Accepts Gold`, level : true, singleline : true},
	Rtn2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Accepts Lumber`, level : true, singleline : true},
	Roa1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Increase (%)`, level : true, singleline : true},
	Roa2: {type: 0, data : 2, name: `(int) Data [multilevel]: Defense Increase`, level : true, singleline : true},
	Roa3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Life Regeneration Rate`, level : true, singleline : true},
	Roa4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Mana Regen`, level : true, singleline : true},
	Roa5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Prefer Hostiles`, level : true, singleline : true},
	Roa6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Prefer Friendlies`, level : true, singleline : true},
	Roa7: {type: 0, data : 7, name: `(int) Data [multilevel]: Max Units`, level : true, singleline : true},
	Nbr1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Increase`, level : true, singleline : true},
	Roo1: {type: 0, data : 1, name: `(attackBits) Data [multilevel]: Rooted Weapons`, level : true, singleline : true},
	Roo2: {type: 0, data : 2, name: `(attackBits) Data [multilevel]: Uprooted Weapons`, level : true, singleline : true},
	Roo3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Rooted Turning`, level : true, singleline : true},
	Roo4: {type: 0, data : 4, name: `(defenseTypeInt) Data [multilevel]: Uprooted Defense Type`, level : true, singleline : true},
	Sal1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Salvage Cost Ratio`, level : true, singleline : true},
	Sal2: {type: 0, data : 2, name: `(int) Data [multilevel]: Accumulation Step`, level : true, singleline : true},
	Esn1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: In Flight Sight Radius`, level : true, singleline : true},
	Esn2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Hovering Sight Radius`, level : true, singleline : true},
	Esn3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Hovering Height`, level : true, singleline : true},
	Esn4: {type: 0, data : 4, name: `(int) Data [multilevel]: Number of Owls`, level : true, singleline : true},
	Esn5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Duration of Owls`, level : true, singleline : true},
	Shm1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Fade Duration`, level : true, singleline : true},
	Shm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Day/Night Duration`, level : true, singleline : true},
	Shm3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Action Duration`, level : true, singleline : true},
	Shm4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Permanent Cloak`, level : true, singleline : true},
	Slo1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Slo2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Slo3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Always Autocast`, level : true, singleline : true},
	Spo1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Spo2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Spo3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Spo4: {type: 0, data : 4, name: `(stackFlags) Data [multilevel]: Stacking Type`, level : true, singleline : true},
	Sod1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Units`, level : true, singleline : true},
	Sod2: {type: 0, data : 2, name: `(unitCode) Data [multilevel]: Unit Type`, level : true, singleline : true},
	Spa1: {type: 0, data : 1, name: `(int) Data [multilevel]: Spider Capacity`, level : true, singleline : true},
	Sta1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Activation Delay`, level : true, singleline : true},
	Sta2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Detection Radius`, level : true, singleline : true},
	Sta3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Detonation Radius`, level : true, singleline : true},
	Sta4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Stun Duration`, level : true, singleline : true},
	Sta5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Detonation Delay`, level : true, singleline : true},
	Stau: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Ward Unit Type`, level : true, singleline : true},
	Uhf1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Speed Bonus (%)`, level : true, singleline : true},
	Uhf2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage per Second`, level : true, singleline : true},
	Wha1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Lumber per Interval`, level : true, singleline : true},
	Wha2: {type: 0, data : 2, name: `(int) Data [multilevel]: Intervals Before Changing Trees`, level : true, singleline : true},
	Wha3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Art Attachment Height`, level : true, singleline : true},
	Wrp1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Teleport Area Width`, level : true, singleline : true},
	Wrp2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Teleport Area Height`, level : true, singleline : true},
	Iagi: {type: 0, data : 1, name: `(int) Data [multilevel]: Agility Bonus`, level : true, singleline : true},
	Iint: {type: 0, data : 2, name: `(int) Data [multilevel]: Intelligence Bonus`, level : true, singleline : true},
	Istr: {type: 0, data : 3, name: `(int) Data [multilevel]: Strength Bonus`, level : true, singleline : true},
	Ihid: {type: 0, data : 4, name: `(bool) Data [multilevel]: Hide Button`, level : true, singleline : true},
	Iatt: {type: 0, data : 1, name: `(int) Data [multilevel]: Attack Bonus`, level : true, singleline : true},
	Idef: {type: 0, data : 1, name: `(int) Data [multilevel]: Defense Bonus`, level : true, singleline : true},
	Isn1: {type: 0, data : 1, name: `(int) Data [multilevel]: Summon 1 - Amount`, level : true, singleline : true},
	Ist1: {type: 0, data : 3, name: `(unitCode) Data [multilevel]: Summon 1 - Unit Type`, level : true, singleline : true},
	Isn2: {type: 0, data : 2, name: `(int) Data [multilevel]: Summon 2 - Amount`, level : true, singleline : true},
	Ist2: {type: 0, data : 4, name: `(unitCode) Data [multilevel]: Summon 2 - Unit Type`, level : true, singleline : true},
	Ixpg: {type: 0, data : 1, name: `(int) Data [multilevel]: Experience Gained`, level : true, singleline : true},
	Ihpg: {type: 0, data : 1, name: `(int) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Impg: {type: 0, data : 1, name: `(int) Data [multilevel]: Mana Points Gained`, level : true, singleline : true},
	Ihp2: {type: 0, data : 2, name: `(int) Data [multilevel]: Hit Points Gained`, level : true, singleline : true},
	Imp2: {type: 0, data : 3, name: `(int) Data [multilevel]: Mana Points Gained`, level : true, singleline : true},
	Ivam: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Stolen Per Attack`, level : true, singleline : true},
	Idic: {type: 0, data : 1, name: `(int) Data [multilevel]: Damage Bonus Dice`, level : true, singleline : true},
	Iarp: {type: 0, data : 2, name: `(int) Data [multilevel]: Armor Penalty`, level : true, singleline : true},
	Idam: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Iob5: {type: 0, data : 5, name: `(int) Data [multilevel]: Enabled Attack Index`, level : true, singleline : true},
	Iob2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Chance To Hit Units (%)`, level : true, singleline : true},
	Iob3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Chance To Hit Heros (%)`, level : true, singleline : true},
	Iob4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Chance To Hit Summons (%)`, level : true, singleline : true},
	Iobu: {type: 3, data : 0, name: `(abilCode) UnitID [multilevel]: Effect Ability`, level : true, singleline : true},
	Ilev: {type: 0, data : 1, name: `(int) Data [multilevel]: Levels Gained`, level : true, singleline : true},
	Ilif: {type: 0, data : 1, name: `(int) Data [multilevel]: Max Life Gained`, level : true, singleline : true},
	Iman: {type: 0, data : 1, name: `(int) Data [multilevel]: Max Mana Gained`, level : true, singleline : true},
	Igol: {type: 0, data : 1, name: `(int) Data [multilevel]: Gold Given`, level : true, singleline : true},
	Ilum: {type: 0, data : 1, name: `(int) Data [multilevel]: Lumber Given`, level : true, singleline : true},
	Ifa1: {type: 0, data : 1, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Idel: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Delay For Target Effect`, level : true, singleline : true},
	Icre: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Imvb: {type: 0, data : 1, name: `(int) Data [multilevel]: Movement Speed Bonus`, level : true, singleline : true},
	Ihpr: {type: 0, data : 1, name: `(int) Data [multilevel]: Hit Points Regenerated Per Second`, level : true, singleline : true},
	Isib: {type: 0, data : 1, name: `(int) Data [multilevel]: Sight Range Bonus`, level : true, singleline : true},
	Icfd: {type: 0, data : 1, name: `(int) Data [multilevel]: Damage Per Duration`, level : true, singleline : true},
	Icfm: {type: 0, data : 2, name: `(int) Data [multilevel]: Mana Used Per Second`, level : true, singleline : true},
	Icfx: {type: 0, data : 3, name: `(int) Data [multilevel]: Extra Mana Required`, level : true, singleline : true},
	Idet: {type: 0, data : 1, name: `(detectionType) Data [multilevel]: Detection Radius`, level : true, singleline : true},
	Idim: {type: 0, data : 1, name: `(int) Data [multilevel]: Mana Loss Per Unit`, level : true, singleline : true},
	Idid: {type: 0, data : 2, name: `(int) Data [multilevel]: Damage To Summoned Units`, level : true, singleline : true},
	Iild: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Dealt (% of normal)`, level : true, singleline : true},
	Iilw: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Received Multiplier`, level : true, singleline : true},
	Irec: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Number of Units`, level : true, singleline : true},
	Imrp: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Regeneration Bonus (as fraction of normal)`, level : true, singleline : true},
	Ircd: {type: 0, data : 1, name: `(int) Data [multilevel]: Delay After Death (seconds)`, level : true, singleline : true},
	irc2: {type: 0, data : 2, name: `(int) Data [multilevel]: Restored Life`, level : true, singleline : true},
	irc3: {type: 0, data : 3, name: `(int) Data [multilevel]: Restored Mana (-1 for current)`, level : true, singleline : true},
	Ihps: {type: 0, data : 1, name: `(int) Data [multilevel]: Hit Points Restored`, level : true, singleline : true},
	Imps: {type: 0, data : 2, name: `(int) Data [multilevel]: Mana Points Restored`, level : true, singleline : true},
	Ispi: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Increase`, level : true, singleline : true},
	Itpm: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Number of Units`, level : true, singleline : true},
	Itp2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Use Teleport Clustering`, level : true, singleline : true},
	Idps: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Cad1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Corpses Raised`, level : true, singleline : true},
	Cac1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Damage Increase`, level : true, singleline : true},
	Cor1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Isx1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attack Speed Increase`, level : true, singleline : true},
	Wrs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Wrs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Terrain Deformation Amplitude`, level : true, singleline : true},
	Wrs3: {type: 0, data : 3, name: `(int) Data [multilevel]: Terrain Deformation Duration (ms)`, level : true, singleline : true},
	Ctc1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Ctc2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Extra Damage To Target`, level : true, singleline : true},
	Ctc3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Movement Speed Reduction`, level : true, singleline : true},
	Ctc4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Attack Speed Reduction`, level : true, singleline : true},
	Ctb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage`, level : true, singleline : true},
	Ibl1: {type: 3, data : 0, name: `(unitList) UnitID [multilevel]: Unit Created (per player race)`, level : true, singleline : true},
	Uds1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Units`, level : true, singleline : true},
	Uds2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Casting Delay (seconds)`, level : true, singleline : true},
	Ndc1: {type: 3, data : 1, name: `(unitRace) Data [multilevel]: Race to Convert`, level : true, singleline : true},
	Ndc2: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Conversion Unit`, level : true, singleline : true},
	Nsl1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Unit to Preserve`, level : true, singleline : true},
	Chl1: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Unit Type Allowed`, level : true, singleline : true},
	Det1: {type: 0, data : 1, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Dtn1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Loss (per unit)`, level : true, singleline : true},
	Dtn2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage to Summoned Units`, level : true, singleline : true},
	Eth1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Immune to Morph Effects`, level : true, singleline : true},
	Eth2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Does Not Block Buildings`, level : true, singleline : true},
	Gho1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Auto-Acquire Attack Targets`, level : true, singleline : true},
	Gho2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Immune to Morph Effects`, level : true, singleline : true},
	Gho3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Does Not Block Buildings`, level : true, singleline : true},
	Ivs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Transition Time (seconds)`, level : true, singleline : true},
	Nmr1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Drained per Second`, level : true, singleline : true},
	Nsp1: {type: 0, data : 1, name: `(int) Data [multilevel]: Gold Cost per Structure`, level : true, singleline : true},
	Nsp2: {type: 0, data : 2, name: `(int) Data [multilevel]: Lumber Cost per Use`, level : true, singleline : true},
	Nsp3: {type: 0, data : 3, name: `(detectionType) Data [multilevel]: Detection Type`, level : true, singleline : true},
	Ssk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Reduce Damage (%)`, level : true, singleline : true},
	Ssk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Minimum Damage`, level : true, singleline : true},
	Ssk3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Ignored Damage`, level : true, singleline : true},
	Ssk4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Include Ranged Damage`, level : true, singleline : true},
	Ssk5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Include Melee Damage`, level : true, singleline : true},
	Hfs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Full Damage Dealt`, level : true, singleline : true},
	Hfs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Full Damage Interval`, level : true, singleline : true},
	Hfs3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Half Damage Dealt`, level : true, singleline : true},
	Hfs4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Half Damage Interval`, level : true, singleline : true},
	Hfs5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Building Reduction`, level : true, singleline : true},
	Hfs6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Maximum Damage`, level : true, singleline : true},
	Nms1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana per Hit Point`, level : true, singleline : true},
	Nms2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Absorbed (%)`, level : true, singleline : true},
	Uim1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Wave Distance`, level : true, singleline : true},
	Uim2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Wave Time (seconds)`, level : true, singleline : true},
	Uim3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Dealt`, level : true, singleline : true},
	Uim4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Air Time (seconds)`, level : true, singleline : true},
	Uim5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Не может быть прервано`, level : true, singleline : true},
	Uim6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Airborne Targets Vulnerable`, level : true, singleline : true},
	Uls1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Swarm Units`, level : true, singleline : true},
	Uls2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Unit Release Interval (seconds)`, level : true, singleline : true},
	Uls3: {type: 0, data : 3, name: `(int) Data [multilevel]: Max Swarm Units Per Target`, level : true, singleline : true},
	Uls4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Damage Return Factor`, level : true, singleline : true},
	Uls5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Damage Return Threshold`, level : true, singleline : true},
	Ulsu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Swarm Unit Type`, level : true, singleline : true},
	Uts1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Returned Damage Factor`, level : true, singleline : true},
	Uts2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Received Damage Factor`, level : true, singleline : true},
	Uts3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Defense Bonus`, level : true, singleline : true},
	Nba1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Nba2: {type: 0, data : 2, name: `(int) Data [multilevel]: Number of Summoned Units`, level : true, singleline : true},
	Nba3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Summoned Unit Duration (seconds)`, level : true, singleline : true},
	Nbau: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	Nch1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Cmg2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana per Summoned Hitpoint`, level : true, singleline : true},
	Cmg3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Charge for Current Life`, level : true, singleline : true},
	Ndr1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Hit Points Drained`, level : true, singleline : true},
	Ndr2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Points Drained`, level : true, singleline : true},
	Ndr3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Drain Interval (seconds)`, level : true, singleline : true},
	Ndr4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Life Transferred Per Second`, level : true, singleline : true},
	Ndr5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Mana Transferred Per Second`, level : true, singleline : true},
	Ndr6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Bonus Life Factor`, level : true, singleline : true},
	Ndr7: {type: 2, data : 7, name: `(unreal) Data [multilevel]: Bonus Life Decay`, level : true, singleline : true},
	Ndr8: {type: 2, data : 8, name: `(unreal) Data [multilevel]: Bonus Mana Factor`, level : true, singleline : true},
	Ndr9: {type: 2, data : 9, name: `(unreal) Data [multilevel]: Bonus Mana Decay`, level : true, singleline : true},
	NdrA: {type: 0, data : 10, name: `(bool) Data [multilevel]: Use Black Arrow Effect`, level : true, singleline : true},
	Nsi1: {type: 0, data : 1, name: `(silenceFlags) Data [multilevel]: Attacks Prevented`, level : true, singleline : true},
	Nsi2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Chance To Miss (%)`, level : true, singleline : true},
	Nsi3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Movement Speed Modifier`, level : true, singleline : true},
	Nsi4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Attack Speed Modifier`, level : true, singleline : true},
	Ntou: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	Tdg1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Tdg2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Medium Damage Radius`, level : true, singleline : true},
	Tdg3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Medium Damage Per Second`, level : true, singleline : true},
	Tdg4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Small Damage Radius`, level : true, singleline : true},
	Tdg5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Small Damage Per Second`, level : true, singleline : true},
	Tsp1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Air Time (seconds)`, level : true, singleline : true},
	Tsp2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Minimum Hit Interval (seconds)`, level : true, singleline : true},
	Nbf5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Ebl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Maximum Range`, level : true, singleline : true},
	Ebl2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Minimum Range`, level : true, singleline : true},
	Efk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Target`, level : true, singleline : true},
	Efk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Maximum Total Damage`, level : true, singleline : true},
	Efk3: {type: 0, data : 3, name: `(int) Data [multilevel]: Maximum Number of Targets`, level : true, singleline : true},
	Efk4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Maximum Speed Adjustment`, level : true, singleline : true},
	Esh1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Decaying Damage`, level : true, singleline : true},
	Esh2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Esh3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Attack Speed Factor`, level : true, singleline : true},
	Esh4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Decay Power`, level : true, singleline : true},
	Esh5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Initial Damage`, level : true, singleline : true},
	Esv1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Summoned Units`, level : true, singleline : true},
	Esvu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	abs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Maximum Life Absorbed`, level : true, singleline : true},
	abs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Maximum Mana Absorbed`, level : true, singleline : true},
	bsk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Increase`, level : true, singleline : true},
	bsk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Increase`, level : true, singleline : true},
	bsk3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Taken Increase`, level : true, singleline : true},
	coau: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Resulting Unit Type`, level : true, singleline : true},
	coa1: {type: 0, data : 1, name: `(unitCode) Data [multilevel]: Partner Unit Type`, level : true, singleline : true},
	coa2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Move To Partner`, level : true, singleline : true},
	cyc1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Can Be Dispelled`, level : true, singleline : true},
	dcp1: {type: 0, data : 1, name: `(unitCode) Data [multilevel]: Partner Unit Type One`, level : true, singleline : true},
	dcp2: {type: 0, data : 2, name: `(unitCode) Data [multilevel]: Partner Unit Type Two`, level : true, singleline : true},
	dvm1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Per Unit`, level : true, singleline : true},
	dvm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Per Unit`, level : true, singleline : true},
	dvm3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Life Per Buff`, level : true, singleline : true},
	dvm4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Mana Per Buff`, level : true, singleline : true},
	dvm5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	dvm6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Ignore Friendly Buffs`, level : true, singleline : true},
	exh1: {type: 0, data : 1, name: `(int) Data [multilevel]: Maximum Number of Corpses`, level : true, singleline : true},
	exhu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Unit Type`, level : true, singleline : true},
	fak1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	fak2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Medium Damage Factor`, level : true, singleline : true},
	fak3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Small Damage Factor`, level : true, singleline : true},
	fak4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Full Damage Radius`, level : true, singleline : true},
	fak5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Half Damage Radius`, level : true, singleline : true},
	hwdu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Ward Unit Type`, level : true, singleline : true},
	inv1: {type: 0, data : 1, name: `(int) Data [multilevel]: Item Capacity`, level : true, singleline : true},
	inv2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Drop Items On Death`, level : true, singleline : true},
	inv3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Can Use Items`, level : true, singleline : true},
	inv4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Can Get Items`, level : true, singleline : true},
	inv5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Can Drop Items`, level : true, singleline : true},
	liq1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Extra Damage Per Second`, level : true, singleline : true},
	liq2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Movement Speed Reduction`, level : true, singleline : true},
	liq3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Attack Speed Reduction`, level : true, singleline : true},
	liq4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Repairs Allowed`, level : true, singleline : true},
	mim1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Magic Damage Factor`, level : true, singleline : true},
	mfl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Unit - Damage Per Mana Point`, level : true, singleline : true},
	mfl2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Hero - Damage Per Mana Point`, level : true, singleline : true},
	mfl3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Unit - Maximum Damage`, level : true, singleline : true},
	mfl4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Hero - Maximum Damage`, level : true, singleline : true},
	mfl5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Damage Cooldown`, level : true, singleline : true},
	mfl6: {type: 0, data : 6, name: `(bool) Data [multilevel]: Caster Only Splash`, level : true, singleline : true},
	tpi1: {type: 0, data : 1, name: `(unitCode) Data [multilevel]: Required Unit Type`, level : true, singleline : true},
	tpi2: {type: 0, data : 2, name: `(unitCode) Data [multilevel]: Converted Unit Type`, level : true, singleline : true},
	spl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Distributed Damage Factor`, level : true, singleline : true},
	spl2: {type: 0, data : 2, name: `(int) Data [multilevel]: Maximum Number of Targets`, level : true, singleline : true},
	irl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Regenerated`, level : true, singleline : true},
	irl2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Regenerated`, level : true, singleline : true},
	irl3: {type: 0, data : 3, name: `(fullFlags) Data [multilevel]: Allow When Full`, level : true, singleline : true},
	irl4: {type: 0, data : 4, name: `(bool) Data [multilevel]: No Target Required`, level : true, singleline : true},
	irl5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Dispel On Attack`, level : true, singleline : true},
	idc1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Mana Loss Per Unit`, level : true, singleline : true},
	idc2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Summoned Unit Damage`, level : true, singleline : true},
	idc3: {type: 0, data : 3, name: `(int) Data [multilevel]: Maximum Dispelled Units`, level : true, singleline : true},
	imo1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Lures`, level : true, singleline : true},
	imo2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Activation Delay`, level : true, singleline : true},
	imo3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Lure Interval (seconds)`, level : true, singleline : true},
	imou: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Lure Unit Type`, level : true, singleline : true},
	ict1: {type: 0, data : 1, name: `(int) Data [multilevel]: New Time of Day - Hour`, level : true, singleline : true},
	ict2: {type: 0, data : 2, name: `(int) Data [multilevel]: New Time of Day - Minute`, level : true, singleline : true},
	isr1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	isr2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Reduction`, level : true, singleline : true},
	ipv1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	ipv2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Life Steal Amount`, level : true, singleline : true},
	ipv3: {type: 0, data : 3, name: `(bool) Data [multilevel]: Amount Is Raw Value`, level : true, singleline : true},
	mec1: {type: 0, data : 1, name: `(int) Data [multilevel]: Number of Units Created`, level : true, singleline : true},
	spb1: {type: 3, data : 1, name: `(abilityList) Data [multilevel]: Spell List`, level : true, singleline : true},
	spb2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Shared Spell Cooldown`, level : true, singleline : true},
	spb3: {type: 0, data : 3, name: `(int) Data [multilevel]: Minimum Spells`, level : true, singleline : true},
	spb4: {type: 0, data : 4, name: `(int) Data [multilevel]: Maximum Spells`, level : true, singleline : true},
	spb5: {type: 3, data : 5, name: `(orderString) Data [multilevel]: Base Order ID`, level : true, singleline : true},
	ast1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Life Restored Factor`, level : true, singleline : true},
	ast2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Mana Restored Factor`, level : true, singleline : true},
	gra1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Attach Delay`, level : true, singleline : true},
	gra2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Remove Delay`, level : true, singleline : true},
	gra3: {type: 0, data : 3, name: `(int) Data [multilevel]: Disabled Attack Index`, level : true, singleline : true},
	gra4: {type: 0, data : 4, name: `(int) Data [multilevel]: Enabled Attack Index`, level : true, singleline : true},
	gra5: {type: 0, data : 5, name: `(int) Data [multilevel]: Maximum Attacks`, level : true, singleline : true},
	ipmu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Unit Type`, level : true, singleline : true},
	Npr1: {type: 0, data : 1, name: `(pickFlags) Data [multilevel]: Building Types Allowed`, level : true, singleline : true},
	Nsa1: {type: 0, data : 1, name: `(pickFlags) Data [multilevel]: Building Types Allowed`, level : true, singleline : true},
	Nsa2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Hero Regeneration Delay`, level : true, singleline : true},
	Nsa3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Unit Regeneration Delay`, level : true, singleline : true},
	Nsa4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Nsa5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Hit Points Per Second`, level : true, singleline : true},
	Iaa1: {type: 0, data : 1, name: `(int) Data [multilevel]: Attack Modification`, level : true, singleline : true},
	Ixs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage To Summoned Units`, level : true, singleline : true},
	Ixs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Magic Damage Reduction`, level : true, singleline : true},
	Nef1: {type: 3, data : 1, name: `(unitList) Data [multilevel]: Summoned Unit Types`, level : true, singleline : true},
	Npa5: {type: 0, data : 5, name: `(int) Data [multilevel]: Summoned Unit Count`, level : true, singleline : true},
	Npa6: {type: 2, data : 0, name: `(unreal) Cast [multilevel]: Summoned Unit Duration`, level : true, singleline : true},
	Igl1: {type: 0, data : 1, name: `(int) Data [multilevel]: Upgrade Levels`, level : true, singleline : true},
	Iglu: {type: 0, data : 0, name: `(upgradeCode) UnitID [multilevel]: Upgrade Type`, level : true, singleline : true},
	Nse1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Shield Cooldown Time`, level : true, singleline : true},
	Ndo1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	Ndo2: {type: 0, data : 2, name: `(int) Data [multilevel]: Number of Summoned Units`, level : true, singleline : true},
	Ndo3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Summoned Unit Duration (seconds)`, level : true, singleline : true},
	Ndo4: {type: 0, data : 4, name: `(int) Data [multilevel]: Maximum Creep Level`, level : true, singleline : true},
	Ndo5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Movement Speed Factor`, level : true, singleline : true},
	Ndou: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Summoned Unit Type`, level : true, singleline : true},
	flk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Medium Damage Radius`, level : true, singleline : true},
	flk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Small Damage Radius`, level : true, singleline : true},
	flk3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Full Damage Amount`, level : true, singleline : true},
	flk4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Medium Damage Amount`, level : true, singleline : true},
	flk5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Small Damage Amount`, level : true, singleline : true},
	Hbn1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Reduction (%)`, level : true, singleline : true},
	Hbn2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Reduction (%)`, level : true, singleline : true},
	fbk1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Max Mana Drained - Units`, level : true, singleline : true},
	fbk2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Ratio - Units (%)`, level : true, singleline : true},
	fbk3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Max Mana Drained - Heros`, level : true, singleline : true},
	fbk4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Damage Ratio - Heros (%)`, level : true, singleline : true},
	fbk5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Summoned Damage`, level : true, singleline : true},
	nca1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Distributed Damage Factor`, level : true, singleline : true},
	pxf1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Initial Damage`, level : true, singleline : true},
	pxf2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	mls1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Per Second`, level : true, singleline : true},
	sla1: {type: 0, data : 1, name: `(bool) Data [multilevel]: Sleep Once`, level : true, singleline : true},
	Nst1: {type: 0, data : 1, name: `(int) Data [multilevel]: Beasts Per Second`, level : true, singleline : true},
	Nst2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Beast Collision Radius`, level : true, singleline : true},
	Nst3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Amount`, level : true, singleline : true},
	Nst4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Damage Radius`, level : true, singleline : true},
	Nst5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Damage Delay`, level : true, singleline : true},
	sla2: {type: 0, data : 2, name: `(bool) Data [multilevel]: Allow On Any Player Slot`, level : true, singleline : true},
	Ncl1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Follow Through Time`, level : true, singleline : true},
	Ncl2: {type: 0, data : 2, name: `(channelType) Data [multilevel]: Target Type`, level : true, singleline : true},
	Ncl3: {type: 0, data : 3, name: `(channelFlags) Data [multilevel]: Options`, level : true, singleline : true},
	Ncl4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Art Duration`, level : true, singleline : true},
	Ncl5: {type: 0, data : 5, name: `(bool) Data [multilevel]: Disable Other Abilities`, level : true, singleline : true},
	Ncl6: {type: 3, data : 6, name: `(orderString) Data [multilevel]: Base Order ID`, level : true, singleline : true},
	Nab1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Movement Speed Reduction (%)`, level : true, singleline : true},
	Nab2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Attack Speed Reduction (%)`, level : true, singleline : true},
	Nab3: {type: 0, data : 3, name: `(int) Data [multilevel]: Armor Penalty`, level : true, singleline : true},
	Nab4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Primary Damage`, level : true, singleline : true},
	Nab5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Secondary Damage`, level : true, singleline : true},
	Nab6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Damage Interval`, level : true, singleline : true},
	Nhs6: {type: 0, data : 6, name: `(int) Data [multilevel]: Wave Count`, level : true, singleline : true},
	Ntm1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Gold Cost Factor`, level : true, singleline : true},
	Ntm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Lumber Cost Factor`, level : true, singleline : true},
	Ntm3: {type: 0, data : 3, name: `(int) Data [multilevel]: Max Creep Level`, level : true, singleline : true},
	Ntm4: {type: 0, data : 4, name: `(bool) Data [multilevel]: Allow Bounty`, level : true, singleline : true},
	Neg1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Move Speed Bonus`, level : true, singleline : true},
	Neg2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Bonus`, level : true, singleline : true},
	Neg3: {type: 3, data : 3, name: `(heroAbilityList) Data [multilevel]: Ability Upgrade 1`, level : true, singleline : true},
	Neg4: {type: 3, data : 4, name: `(heroAbilityList) Data [multilevel]: Ability Upgrade 2`, level : true, singleline : true},
	Neg5: {type: 3, data : 5, name: `(heroAbilityList) Data [multilevel]: Ability Upgrade 3`, level : true, singleline : true},
	Neg6: {type: 3, data : 6, name: `(heroAbilityList) Data [multilevel]: Ability Upgrade 4`, level : true, singleline : true},
	Ncs1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Amount`, level : true, singleline : true},
	Ncs2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Interval`, level : true, singleline : true},
	Ncs3: {type: 0, data : 3, name: `(int) Data [multilevel]: Missile Count`, level : true, singleline : true},
	Ncs4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Max Damage`, level : true, singleline : true},
	Ncs5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Building Damage Factor`, level : true, singleline : true},
	Ncs6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Effect Duration`, level : true, singleline : true},
	Nsy1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Spawn Interval`, level : true, singleline : true},
	Nsy2: {type: 0, data : 2, name: `(unitCode) Data [multilevel]: Spawn Unit ID`, level : true, singleline : true},
	Nsy3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Spawn Unit Duration`, level : true, singleline : true},
	Nsy4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Spawn Unit Offset`, level : true, singleline : true},
	Nsy5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Leash Range`, level : true, singleline : true},
	Nsyu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Factory Unit ID`, level : true, singleline : true},
	Nfy1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Spawn Interval`, level : true, singleline : true},
	Nfy2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Leash Range`, level : true, singleline : true},
	Nfyu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Spawn Unit ID`, level : true, singleline : true},
	Nde1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Chance to Demolish`, level : true, singleline : true},
	Nde2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Multiplier (Buildings)`, level : true, singleline : true},
	Nde3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Multiplier (Units)`, level : true, singleline : true},
	Nde4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Damage Multiplier (Heroes)`, level : true, singleline : true},
	Nic1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Bonus Damage Multiplier`, level : true, singleline : true},
	Nic2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Death Damage Full Amount`, level : true, singleline : true},
	Nic3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Death Damage Full Area`, level : true, singleline : true},
	Nic4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Death Damage Half Amount`, level : true, singleline : true},
	Nic5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Death Damage Half Area`, level : true, singleline : true},
	Nic6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Death Damage Delay`, level : true, singleline : true},
	Nso1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Damage Amount`, level : true, singleline : true},
	Nso2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Damage Period`, level : true, singleline : true},
	Nso3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Damage Penalty`, level : true, singleline : true},
	Nso4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Movement Speed Reduction (%)`, level : true, singleline : true},
	Nso5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Attack Speed Reduction (%)`, level : true, singleline : true},
	Nlm2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Split Delay`, level : true, singleline : true},
	Nlm3: {type: 0, data : 3, name: `(int) Data [multilevel]: Split Attack Count`, level : true, singleline : true},
	Nlm4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Max Hitpoint Factor`, level : true, singleline : true},
	Nlm5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Life Duration Split Bonus`, level : true, singleline : true},
	Nlm6: {type: 0, data : 6, name: `(int) Data [multilevel]: Generation Count`, level : true, singleline : true},
	Nvc1: {type: 0, data : 1, name: `(int) Data [multilevel]: Rock Ring Count`, level : true, singleline : true},
	Nvc2: {type: 0, data : 2, name: `(int) Data [multilevel]: Wave Count`, level : true, singleline : true},
	Nvc3: {type: 2, data : 3, name: `(unreal) Data [multilevel]: Wave Interval`, level : true, singleline : true},
	Nvc4: {type: 2, data : 4, name: `(unreal) Data [multilevel]: Building Damage Factor`, level : true, singleline : true},
	Nvc5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Full Damage Amount`, level : true, singleline : true},
	Nvc6: {type: 2, data : 6, name: `(unreal) Data [multilevel]: Half Damage Factor`, level : true, singleline : true},
	Nvcu: {type: 0, data : 0, name: `(unitCode) UnitID [multilevel]: Destructible ID`, level : true, singleline : true},
	Tau1: {type: 0, data : 1, name: `(int) Data [multilevel]: Prefer Hostiles`, level : true, singleline : true},
	Tau2: {type: 0, data : 2, name: `(int) Data [multilevel]: Prefer Friendlies`, level : true, singleline : true},
	Tau3: {type: 0, data : 3, name: `(int) Data [multilevel]: Max Units`, level : true, singleline : true},
	Tau4: {type: 0, data : 4, name: `(int) Data [multilevel]: Number of Pulses`, level : true, singleline : true},
	Tau5: {type: 2, data : 5, name: `(unreal) Data [multilevel]: Interval between Pulses`, level : true, singleline : true},
	Idg1: {type: 0, data : 2, name: `(bool) Data [multilevel]: Requires Undead Target`, level : true, singleline : true},
	Idg2: {type: 0, data : 3, name: `(bool) Data [multilevel]: Affects Initial Target`, level : true, singleline : true},
	Idg3: {type: 3, data : 8, name: `(targetList) Data [multilevel]: Targets Allowed for Heal`, level : true, singleline : true},
	Uuf1: {type: 0, data : 3, name: `(bool) Data [multilevel]: Requires Undead Target`, level : true, singleline : true},
	Uuf2: {type: 0, data : 4, name: `(bool) Data [multilevel]: Leave Target Alive`, level : true, singleline : true},
	Uuf3: {type: 3, data : 8, name: `(targetList) Data [multilevel]: Targets Allowed for Buff`, level : true, singleline : true},
	Hsb1: {type: 2, data : 1, name: `(unreal) Data [multilevel]: Bonus Damage (Flat)`, level : true, singleline : true},
	Hsb2: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Bonus Damage (Percent)`, level : true, singleline : true},
	Hsb3: {type: 0, data : 3, name: `(defenseTypeInt) Data [multilevel]: Defense Type Affected`, level : true, singleline : true},
	Iofr: {type: 2, data : 2, name: `(unreal) Data [multilevel]: Healing Multiplier`, level : true, singleline : true},
	AIvu: {type: 0, data : 1, name: `(bool) Data [multilevel]: Is Magic Immune`, level : true, singleline : true},
	Akb2: {type: 0, data : 5, name: `(bool) Data [multilevel]: Play Channel Animation`, level : true, singleline : true},
	ausk: {type: 3, data : 0, name: `(unitSkinList) UnitSkinID: Unit Skin List`, singleline : true},
	Aat1: {type: 0, data : 1, name: `(bool) Data [multilevel]: По умолчанию включено`, level : true, singleline : true},

};
export default map;