[Settings]
version = 3 # binary format version

[NTiw] # 1314154871 0x4e546977
# (unreal) radius : Elevation Sample Radius
brad = 0.1
# (bool) fatLOS : Fat Line of Sight
bflo = 1
# (unreal) flyH : Fly-Over Height
bflh = 169.9
# (unreal) fogRadius : Fog Radius
bfra = 0.1
# (bool) fogVis : Fog Visibility
bfvi = 1
# (unreal) occH : Occlusion Height
boch = 229.9
# (bool) selectable : Selectable In Game
bgse = 1
# (armorType) armor : Armor Type
barm = "Metal"
# (targetList) targType : Targeted As
btar = "friend,ground,tree"
# (destructableCategory) category : Category
bcat = "P"
# (bool) tilesetSpecific : Has Tileset Specific Data
btsp = 1
# (bool) UserList : On User-Specified List
busr = 1
# (bool) onCliffs : Placeable on Cliffs
bonc = 1
# (bool) onWater : Placeable on Water
bonw = 0
# (bool) canPlaceDead : Show Dead Version in Palette
bcpd = 0
# (tilesetList) tilesets : Tilesets
btil = "W,N"
# (int) cliffHeight : Cliff Height
bclh = 1
# (bool) walkable : Is Walkable
bwal = 1
# (int) buildTime : Build Time
bbut = 2
# (unreal) HP : Hit Points
bhps = 50.1
# (int) goldRep : Repair Gold Cost
breg = 1
# (int) lumberRep : Repair Lumber Cost
brel = 1
# (int) repairTime : Repair Time
bret = 2
