/** @type {Object.<string, W3ABDHQTUTOMLMapProperty>} */
const map = {
    Adm1: {type: 1, name: 'MANA_LOSS_ADM1', level: true},
    Adm2: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_ADM2', level: true},
    Akb1: {type: 1, name: 'ATTACK_DAMAGE_INCREASE_AKB1', level: true},
    Ams1: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_AMS1', level: true},
    Ams2: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_AMS2', level: true},
    Ams3: {type: 0, name: 'SHIELD_LIFE', level: true},
    Ams4: {type: 0, name: 'MANA_LOSS_AMS4', level: true},
    Ans5: {type: 3, name: 'BASE_ORDER_ID_ANS5', level: true, multiline: true},
    Ans6: {type: 0, name: 'CHARGE_OWNING_PLAYER (boolean)', level: true},
    Apl1: {type: 1, name: 'AURA_DURATION', level: true},
    Apl2: {type: 1, name: 'DAMAGE_PER_SECOND_APL2', level: true},
    Apl3: {type: 1, name: 'DURATION_OF_PLAGUE_WARD', level: true},
    Aplu: {type: 0, name: 'PLAGUE_WARD_UNIT_TYPE', level: true},
    Arm1: {type: 1, name: 'AMOUNT_REGENERATED', level: true},
    Arm2: {type: 0, name: 'PERCENTAGE_ARM2 (boolean)', level: true},
    Bgm1: {type: 0, name: 'GOLD_PER_INTERVAL_BGM1', level: true},
    Bgm2: {type: 1, name: 'INTERVAL_DURATION_BGM2', level: true},
    Bgm3: {type: 0, name: 'MAX_NUMBER_OF_MINERS', level: true},
    Bgm4: {type: 1, name: 'RADIUS_OF_MINING_RING', level: true},
    Bli1: {type: 1, name: 'EXPANSION_AMOUNT', level: true},
    Bli2: {type: 0, name: 'CREATES_BLIGHT (boolean)', level: true},
    Blo1: {type: 1, name: 'ATTACK_SPEED_INCREASE_PERCENT_BLO1', level: true},
    Blo2: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_PERCENT_BLO2', level: true},
    Blo3: {type: 1, name: 'SCALING_FACTOR', level: true},
    Btl1: {type: 0, name: 'ALLOWED_UNIT_TYPE_BTL1', level: true},
    Btl2: {type: 0, name: 'SUMMON_BUSY_UNITS (boolean)', level: true},
    Cac1: {type: 1, name: 'ATTACK_DAMAGE_INCREASE_CAC1', level: true},
    Cad1: {type: 0, name: 'NUMBER_OF_CORPSES_RAISED_CAD1', level: true},
    Can1: {type: 1, name: 'HIT_POINTS_PER_SECOND_CAN1', level: true},
    Can2: {type: 1, name: 'MAX_HIT_POINTS', level: true},
    Car1: {type: 0, name: 'CARGO_CAPACITY', level: true},
    Cha1: {type: 0, name: 'NEW_UNIT_TYPE', level: true},
    Chd1: {type: 1, name: 'MOVEMENT_UPDATE_FREQUENCY_CHD1', level: true},
    Chd2: {type: 1, name: 'ATTACK_UPDATE_FREQUENCY_CHD2', level: true},
    Chd3: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_CHD3', level: true},
    Chl1: {type: 0, name: 'UNIT_TYPE_ALLOWED', level: true},
    Cmg2: {type: 1, name: 'MANA_PER_SUMMONED_HITPOINT', level: true},
    Cmg3: {type: 1, name: 'CHARGE_FOR_CURRENT_LIFE', level: true},
    Cor1: {type: 1, name: 'DAMAGE_PER_SECOND_COR1', level: true},
    Cri1: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_PERCENT_CRI1', level: true},
    Cri2: {type: 1, name: 'ATTACK_SPEED_REDUCTION_PERCENT_CRI2', level: true},
    Cri3: {type: 1, name: 'DAMAGE_REDUCTION_CRI3', level: true},
    Crs1: {type: 1, name: 'CHANCE_TO_MISS_CRS', level: true},
    Ctb1: {type: 1, name: 'DAMAGE_CTB1', level: true},
    Ctc1: {type: 1, name: 'DAMAGE_CTC1', level: true},
    Ctc2: {type: 1, name: 'EXTRA_DAMAGE_TO_TARGET', level: true},
    Ctc3: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_CTC3', level: true},
    Ctc4: {type: 1, name: 'ATTACK_SPEED_REDUCTION_CTC4', level: true},
    Dda1: {type: 1, name: 'FULL_DAMAGE_RADIUS_DDA1', level: true},
    Dda2: {type: 1, name: 'FULL_DAMAGE_AMOUNT_DDA2', level: true},
    Dda3: {type: 1, name: 'PARTIAL_DAMAGE_RADIUS', level: true},
    Dda4: {type: 1, name: 'PARTIAL_DAMAGE_AMOUNT', level: true},
    Def1: {type: 1, name: 'DAMAGE_TAKEN_PERCENT_DEF1', level: true},
    Def2: {type: 1, name: 'DAMAGE_DEALT_PERCENT_DEF2', level: true},
    Def3: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_DEF3', level: true},
    Def4: {type: 1, name: 'ATTACK_SPEED_FACTOR_DEF4', level: true},
    Def5: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_DEF5', level: true},
    Def6: {type: 1, name: 'CHANCE_TO_DEFLECT', level: true},
    Def7: {type: 1, name: 'DEFLECT_DAMAGE_TAKEN_PIERCING', level: true},
    Def8: {type: 1, name: 'DEFLECT_DAMAGE_TAKEN_SPELLS', level: true},
    Det1: {type: 0, name: 'DETECTION_TYPE_DET1', level: true},
    Dev1: {type: 0, name: 'MAX_CREEP_LEVEL_DEV1', level: true},
    Dev2: {type: 1, name: 'DAMAGE_PER_SECOND_DEV2', level: true},
    Dev3: {type: 0, name: 'MAXIMUM_CREEP_LEVEL_DEV3', level: true},
    Dtn1: {type: 1, name: 'MANA_LOSS_PER_UNIT_DTN1', level: true},
    Dtn2: {type: 1, name: 'DAMAGE_TO_SUMMONED_UNITS_DTN2', level: true},
    Eah1: {type: 1, name: 'DAMAGE_DEALT_TO_ATTACKERS', level: true},
    Eah2: {type: 0, name: 'DAMAGE_IS_PERCENT_RECEIVED (boolean)', level: true},
    Ear1: {type: 1, name: 'DAMAGE_BONUS_PERCENT', level: true},
    Ear2: {type: 0, name: 'MELEE_BONUS (boolean)', level: true},
    Ear3: {type: 0, name: 'RANGED_BONUS (boolean)', level: true},
    Ear4: {type: 0, name: 'FLAT_BONUS (boolean)', level: true},
    Eat1: {type: 1, name: 'RIP_DELAY', level: true},
    Eat2: {type: 1, name: 'EAT_DELAY', level: true},
    Eat3: {type: 1, name: 'HIT_POINTS_GAINED_EAT3', level: true},
    Ebl1: {type: 1, name: 'MAXIMUM_RANGE', level: true},
    Ebl2: {type: 1, name: 'MINIMUM_RANGE', level: true},
    Eer1: {type: 1, name: 'DAMAGE_PER_SECOND_EER1', level: true},
    Eev1: {type: 1, name: 'CHANCE_TO_EVADE_EEV1', level: true},
    Efk1: {type: 1, name: 'DAMAGE_PER_TARGET_EFK1', level: true},
    Efk2: {type: 1, name: 'MAXIMUM_TOTAL_DAMAGE', level: true},
    Efk3: {type: 0, name: 'MAXIMUM_NUMBER_OF_TARGETS_EFK3', level: true},
    Efk4: {type: 1, name: 'MAXIMUM_SPEED_ADJUSTMENT', level: true},
    Efn1: {type: 0, name: 'NUMBER_OF_SUMMONED_UNITS_EFN1', level: true},
    Efnu: {type: 0, name: 'SUMMONED_UNIT_TYPE_EFNU', level: true},
    Egm1: {type: 0, name: 'GOLD_PER_INTERVAL_EGM1', level: true},
    Egm2: {type: 1, name: 'INTERVAL_DURATION_EGM2', level: true},
    Eim1: {type: 1, name: 'DAMAGE_PER_INTERVAL', level: true},
    Eim2: {type: 1, name: 'MANA_DRAINED_PER_SECOND_EIM2', level: true},
    Eim3: {type: 1, name: 'BUFFER_MANA_REQUIRED', level: true},
    Emb1: {type: 1, name: 'MAX_MANA_DRAINED', level: true},
    Emb2: {type: 1, name: 'BOLT_DELAY', level: true},
    Emb3: {type: 1, name: 'BOLT_LIFETIME', level: true},
    Eme1: {type: 3, name: 'NORMAL_FORM_UNIT_EME1', level: true, multiline: true},
    Eme2: {type: 0, name: 'MORPHING_FLAGS', level: true},
    Eme3: {type: 1, name: 'ALTITUDE_ADJUSTMENT_DURATION', level: true},
    Eme4: {type: 1, name: 'LANDING_DELAY_TIME', level: true},
    Eme5: {type: 1, name: 'ALTERNATE_FORM_HIT_POINT_BONUS', level: true},
    Emeu: {type: 0, name: 'ALTERNATE_FORM_UNIT_EMEU', level: true},
    Ens1: {type: 1, name: 'AIR_UNIT_LOWER_DURATION', level: true},
    Ens2: {type: 1, name: 'AIR_UNIT_HEIGHT', level: true},
    Ens3: {type: 1, name: 'MELEE_ATTACK_RANGE', level: true},
    Esf1: {type: 1, name: 'DAMAGE_DEALT_ESF1', level: true},
    Esf2: {type: 1, name: 'DAMAGE_INTERVAL_ESF2', level: true},
    Esf3: {type: 1, name: 'BUILDING_REDUCTION_ESF3', level: true},
    Esh1: {type: 1, name: 'DECAYING_DAMAGE', level: true},
    Esh2: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_ESH2', level: true},
    Esh3: {type: 1, name: 'ATTACK_SPEED_FACTOR_ESH3', level: true},
    Esh4: {type: 1, name: 'DECAY_POWER', level: true},
    Esh5: {type: 1, name: 'INITIAL_DAMAGE_ESH5', level: true},
    Esn1: {type: 1, name: 'IN_FLIGHT_SIGHT_RADIUS', level: true},
    Esn2: {type: 1, name: 'HOVERING_SIGHT_RADIUS', level: true},
    Esn3: {type: 1, name: 'HOVERING_HEIGHT', level: true},
    Esn4: {type: 0, name: 'NUMBER_OF_OWLS', level: true},
    Esn5: {type: 1, name: 'DURATION_OF_OWLS', level: true},
    Esv1: {type: 0, name: 'NUMBER_OF_SUMMONED_UNITS_ESV1', level: true},
    Esvu: {type: 0, name: 'SUMMONED_UNIT_TYPE_ESVU', level: true},
    Eth1: {type: 0, name: 'IMMUNE_TO_MORPH_EFFECTS (boolean)', level: true},
    Eth2: {type: 0, name: 'DOES_NOT_BLOCK_BUILDINGS (boolean)', level: true},
    Etq1: {type: 1, name: 'LIFE_HEALED', level: true},
    Etq2: {type: 1, name: 'HEAL_INTERVAL', level: true},
    Etq3: {type: 1, name: 'BUILDING_REDUCTION_ETQ3', level: true},
    Etq4: {type: 1, name: 'INITIAL_IMMUNITY_DURATION', level: true},
    Fae1: {type: 0, name: 'DEFENSE_REDUCTION', level: true},
    Fae2: {type: 0, name: 'ALWAYS_AUTOCAST_FAE2 (boolean)', level: true},
    Fla1: {type: 0, name: 'DETECTION_TYPE_FLA1', level: true},
    Fla2: {type: 1, name: 'EFFECT_DELAY_FLA2', level: true},
    Fla3: {type: 0, name: 'FLARE_COUNT', level: true},
    Gho1: {type: 0, name: 'AUTO_ACQUIRE_ATTACK_TARGETS (boolean)', level: true},
    Gho2: {type: 0, name: 'IMMUNE_TO_MORPH_EFFECTS_GHO2 (boolean)', level: true},
    Gho3: {type: 0, name: 'DO_NOT_BLOCK_BUILDINGS (boolean)', level: true},
    Gld1: {type: 0, name: 'MAX_GOLD', level: true},
    Gld2: {type: 1, name: 'MINING_DURATION', level: true},
    Gld3: {type: 0, name: 'MINING_CAPACITY', level: true},
    Gyd1: {type: 0, name: 'MAXIMUM_NUMBER_OF_CORPSES_GYD1', level: true},
    Gyd2: {type: 1, name: 'RADIUS_OF_GRAVESTONES', level: true},
    Gyd3: {type: 1, name: 'RADIUS_OF_CORPSES', level: true},
    Gydu: {type: 0, name: 'CORPSE_UNIT_TYPE', level: true},
    Hab1: {type: 1, name: 'MANA_REGENERATION_INCREASE', level: true},
    Hab2: {type: 0, name: 'PERCENT_BONUS_HAB2 (boolean)', level: true},
    Had1: {type: 1, name: 'ARMOR_BONUS_HAD1', level: true},
    Had2: {type: 0, name: 'PERCENT_BONUS_HAD2 (boolean)', level: true},
    Har1: {type: 0, name: 'DAMAGE_TO_TREE', level: true},
    Har2: {type: 0, name: 'LUMBER_CAPACITY', level: true},
    Har3: {type: 0, name: 'GOLD_CAPACITY', level: true},
    Hav1: {type: 1, name: 'DEFENSE_BONUS_HAV1', level: true},
    Hav2: {type: 1, name: 'HIT_POINT_BONUS', level: true},
    Hav3: {type: 1, name: 'DAMAGE_BONUS_HAV3', level: true},
    Hav4: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_HAV4', level: true},
    Hbh1: {type: 1, name: 'CHANCE_TO_BASH', level: true},
    Hbh2: {type: 1, name: 'DAMAGE_MULTIPLIER_HBH2', level: true},
    Hbh3: {type: 1, name: 'DAMAGE_BONUS_HBH3', level: true},
    Hbh4: {type: 1, name: 'CHANCE_TO_MISS_HBH4', level: true},
    Hbh5: {type: 0, name: 'NEVER_MISS_HBH5 (boolean)', level: true},
    Hbn1: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_PERCENT_HBN1', level: true},
    Hbn2: {type: 1, name: 'ATTACK_SPEED_REDUCTION_PERCENT_HBN2', level: true},
    Hbz1: {type: 0, name: 'NUMBER_OF_WAVES', level: true},
    Hbz2: {type: 1, name: 'DAMAGE_HBZ2', level: true},
    Hbz3: {type: 0, name: 'NUMBER_OF_SHARDS', level: true},
    Hbz4: {type: 1, name: 'BUILDING_REDUCTION_HBZ4', level: true},
    Hbz5: {type: 1, name: 'DAMAGE_PER_SECOND_HBZ5', level: true},
    Hbz6: {type: 1, name: 'MAXIMUM_DAMAGE_PER_WAVE', level: true},
    Hca1: {type: 1, name: 'EXTRA_DAMAGE_HCA1', level: true},
    Hca2: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_HCA2', level: true},
    Hca3: {type: 1, name: 'ATTACK_SPEED_FACTOR_HCA3', level: true},
    Hca4: {type: 0, name: 'STACK_FLAGS', level: true},
    Hds1: {type: 0, name: 'CAN_DEACTIVATE (boolean)', level: true},
    Hea1: {type: 1, name: 'HIT_POINTS_GAINED_HEA1', level: true},
    Hfa1: {type: 1, name: 'DAMAGE_BONUS_HFA1', level: true},
    Hfs1: {type: 1, name: 'FULL_DAMAGE_DEALT', level: true},
    Hfs2: {type: 1, name: 'FULL_DAMAGE_INTERVAL', level: true},
    Hfs3: {type: 1, name: 'HALF_DAMAGE_DEALT', level: true},
    Hfs4: {type: 1, name: 'HALF_DAMAGE_INTERVAL', level: true},
    Hfs5: {type: 1, name: 'BUILDING_REDUCTION_HFS5', level: true},
    Hfs6: {type: 1, name: 'MAXIMUM_DAMAGE_HFS6', level: true},
    Hhb1: {type: 1, name: 'AMOUNT_HEALED_DAMAGED_HHB1', level: true},
    Hmt1: {type: 0, name: 'NUMBER_OF_UNITS_TELEPORTED', level: true},
    Hmt2: {type: 1, name: 'CASTING_DELAY', level: true},
    Hmt3: {type: 0, name: 'USE_TELEPORT_CLUSTERING_HMT3 (boolean)', level: true},
    Hre1: {type: 0, name: 'NUMBER_OF_CORPSES_RAISED_HRE1', level: true},
    Hre2: {type: 0, name: 'RAISED_UNITS_ARE_INVULNERABLE (boolean)', level: true},
    Htb1: {type: 1, name: 'DAMAGE_HTB1', level: true},
    Htc1: {type: 1, name: 'AOE_DAMAGE', level: true},
    Htc2: {type: 1, name: 'SPECIFIC_TARGET_DAMAGE_HTC2', level: true},
    Htc3: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_PERCENT_HTC3', level: true},
    Htc4: {type: 1, name: 'ATTACK_SPEED_REDUCTION_PERCENT_HTC4', level: true},
    Hwe1: {type: 0, name: 'SUMMONED_UNIT_TYPE_HWE1', level: true},
    Hwe2: {type: 0, name: 'SUMMONED_UNIT_COUNT_HWE2', level: true},
    Iaa1: {type: 0, name: 'ATTACK_MODIFICATION', level: true},
    Iagi: {type: 0, name: 'AGILITY_BONUS', level: true},
    Iarp: {type: 0, name: 'ARMOR_PENALTY_IARP', level: true},
    Iatt: {type: 0, name: 'ATTACK_BONUS', level: true},
    Icfd: {type: 0, name: 'DAMAGE_PER_DURATION', level: true},
    Icfm: {type: 0, name: 'MANA_USED_PER_SECOND', level: true},
    Icfx: {type: 0, name: 'EXTRA_MANA_REQUIRED', level: true},
    Icre: {type: 0, name: 'MAXIMUM_CREEP_LEVEL_ICRE', level: true},
    Idam: {type: 1, name: 'DAMAGE_BONUS_IDAM', level: true},
    Idef: {type: 0, name: 'DEFENSE_BONUS_IDEF', level: true},
    Idel: {type: 1, name: 'DELAY_FOR_TARGET_EFFECT', level: true},
    Idet: {type: 0, name: 'DETECTION_RADIUS_IDET', level: true},
    Idic: {type: 0, name: 'DAMAGE_BONUS_DICE', level: true},
    Idid: {type: 0, name: 'DAMAGE_TO_SUMMONED_UNITS_IDID', level: true},
    Idim: {type: 0, name: 'MANA_LOSS_PER_UNIT_IDIM', level: true},
    Idps: {type: 1, name: 'DAMAGE_PER_SECOND_IDPS', level: true},
    Ifa1: {type: 0, name: 'DETECTION_TYPE_IFA1', level: true},
    Igl1: {type: 0, name: 'UPGRADE_LEVELS', level: true},
    Iglu: {type: 0, name: 'UPGRADE_TYPE', level: true},
    Igol: {type: 0, name: 'GOLD_GIVEN', level: true},
    Ihid: {type: 0, name: 'HIDE_BUTTON (boolean)', level: true},
    Ihp2: {type: 0, name: 'HIT_POINTS_GAINED_IHP2', level: true},
    Ihpg: {type: 0, name: 'HIT_POINTS_GAINED_IHPG', level: true},
    Ihpr: {type: 0, name: 'HIT_POINTS_REGENERATED_PER_SECOND', level: true},
    Ihps: {type: 0, name: 'HIT_POINTS_RESTORED', level: true},
    Iild: {type: 1, name: 'DAMAGE_DEALT_PERCENT_OF_NORMAL', level: true},
    Iilw: {type: 1, name: 'DAMAGE_RECEIVED_MULTIPLIER', level: true},
    Iint: {type: 0, name: 'INTELLIGENCE_BONUS', level: true},
    Ilev: {type: 0, name: 'LEVELS_GAINED', level: true},
    Ilif: {type: 0, name: 'MAX_LIFE_GAINED', level: true},
    Ilum: {type: 0, name: 'LUMBER_GIVEN', level: true},
    Iman: {type: 0, name: 'MAX_MANA_GAINED', level: true},
    Imp2: {type: 0, name: 'MANA_POINTS_GAINED_IMP2', level: true},
    Impg: {type: 0, name: 'MANA_POINTS_GAINED_IMPG', level: true},
    Imps: {type: 0, name: 'MANA_POINTS_RESTORED', level: true},
    Imrp: {type: 1, name: 'MANA_REGENERATION_BONUS_AS_FRACTION_OF_NORMAL', level: true},
    Imvb: {type: 0, name: 'MOVEMENT_SPEED_BONUS', level: true},
    Inf1: {type: 1, name: 'DAMAGE_INCREASE_PERCENT_INF1', level: true},
    Inf2: {type: 0, name: 'DEFENSE_INCREASE_INF2', level: true},
    Inf3: {type: 1, name: 'AUTOCAST_RANGE', level: true},
    Inf4: {type: 1, name: 'LIFE_REGEN_RATE', level: true},
    Iob2: {type: 1, name: 'CHANCE_TO_HIT_UNITS_PERCENT', level: true},
    Iob3: {type: 1, name: 'CHANCE_TO_HIT_HEROS_PERCENT', level: true},
    Iob4: {type: 1, name: 'CHANCE_TO_HIT_SUMMONS_PERCENT', level: true},
    Iob5: {type: 0, name: 'ENABLED_ATTACK_INDEX_IOB5', level: true},
    Iobu: {type: 0, name: 'EFFECT_ABILITY', level: true},
    Ircd: {type: 0, name: 'DELAY_AFTER_DEATH_SECONDS', level: true},
    Irec: {type: 0, name: 'MAXIMUM_NUMBER_OF_UNITS_IREC', level: true},
    Isib: {type: 0, name: 'SIGHT_RANGE_BONUS', level: true},
    Isn1: {type: 0, name: 'SUMMON_1_AMOUNT', level: true},
    Isn2: {type: 0, name: 'SUMMON_2_AMOUNT', level: true},
    Ispi: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_ISPI', level: true},
    Ist1: {type: 3, name: 'SUMMON_1_UNIT_TYPE', level: true, multiline: true},
    Ist2: {type: 3, name: 'SUMMON_2_UNIT_TYPE', level: true, multiline: true},
    Istr: {type: 0, name: 'STRENGTH_BONUS_ISTR', level: true},
    Isx1: {type: 1, name: 'ATTACK_SPEED_INCREASE_ISX1', level: true},
    Itp2: {type: 0, name: 'USE_TELEPORT_CLUSTERING_ITP2 (boolean)', level: true},
    Itpm: {type: 0, name: 'MAXIMUM_NUMBER_OF_UNITS_ITPM', level: true},
    Ivam: {type: 1, name: 'LIFE_STOLEN_PER_ATTACK', level: true},
    Ivs1: {type: 1, name: 'TRANSITION_TIME_SECONDS', level: true},
    Ixpg: {type: 0, name: 'EXPERIENCE_GAINED', level: true},
    Ixs1: {type: 1, name: 'DAMAGE_TO_SUMMONED_UNITS_IXS1', level: true},
    Ixs2: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_IXS2', level: true},
    Lit1: {type: 1, name: 'GRAPHIC_DELAY_LIT1', level: true},
    Lit2: {type: 1, name: 'GRAPHIC_DURATION_LIT2', level: true},
    Loa1: {type: 0, name: 'ALLOWED_UNIT_TYPE_LOA1', level: true},
    Lsh1: {type: 1, name: 'DAMAGE_PER_SECOND_LSH1', level: true},
    Mbt1: {type: 1, name: 'MANA_GAINED', level: true},
    Mbt2: {type: 1, name: 'HIT_POINTS_GAINED_MBT2', level: true},
    Mbt3: {type: 1, name: 'AUTOCAST_REQUIREMENT', level: true},
    Mbt4: {type: 1, name: 'WATER_HEIGHT', level: true},
    Mbt5: {type: 0, name: 'REGENERATE_ONLY_AT_NIGHT (boolean)', level: true},
    Mil1: {type: 3, name: 'NORMAL_FORM_UNIT_MIL1', level: true, multiline: true},
    Mil2: {type: 3, name: 'ALTERNATE_FORM_UNIT_MIL2', level: true, multiline: true},
    Min1: {type: 1, name: 'ACTIVATION_DELAY_MIN1', level: true},
    Min2: {type: 1, name: 'INVISIBILITY_TRANSITION_TIME', level: true},
    Nab1: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_PERCENT_NAB1', level: true},
    Nab2: {type: 1, name: 'ATTACK_SPEED_REDUCTION_PERCENT_NAB2', level: true},
    Nab3: {type: 0, name: 'ARMOR_PENALTY_NAB3', level: true},
    Nab4: {type: 1, name: 'PRIMARY_DAMAGE', level: true},
    Nab5: {type: 1, name: 'SECONDARY_DAMAGE', level: true},
    Nab6: {type: 1, name: 'DAMAGE_INTERVAL_NAB6', level: true},
    Nba1: {type: 1, name: 'DAMAGE_BONUS_NBA1', level: true},
    Nba2: {type: 0, name: 'NUMBER_OF_SUMMONED_UNITS_NBA2', level: true},
    Nba3: {type: 1, name: 'SUMMONED_UNIT_DURATION_SECONDS_NBA3', level: true},
    Nbau: {type: 0, name: 'SUMMONED_UNIT_TYPE_NBAU', level: true},
    Nbf5: {type: 1, name: 'DAMAGE_PER_SECOND_NBF5', level: true},
    Nbr1: {type: 1, name: 'DAMAGE_INCREASE', level: true},
    Nch1: {type: 0, name: 'MAXIMUM_CREEP_LEVEL_NCH1', level: true},
    Ncl1: {type: 1, name: 'FOLLOW_THROUGH_TIME', level: true},
    Ncl2: {type: 0, name: 'TARGET_TYPE', level: true},
    Ncl3: {type: 0, name: 'OPTIONS', level: true},
    Ncl4: {type: 1, name: 'ART_DURATION', level: true},
    Ncl5: {type: 0, name: 'DISABLE_OTHER_ABILITIES (boolean)', level: true},
    Ncl6: {type: 3, name: 'BASE_ORDER_ID_NCL6', level: true, multiline: true},
    Ncr5: {type: 1, name: 'MOVE_SPEED_BONUS_INFO_PANEL_ONLY', level: true},
    Ncr6: {type: 1, name: 'ATTACK_SPEED_BONUS_INFO_PANEL_ONLY', level: true},
    Ncs1: {type: 1, name: 'DAMAGE_AMOUNT_NCS1', level: true},
    Ncs2: {type: 1, name: 'DAMAGE_INTERVAL_NCS2', level: true},
    Ncs3: {type: 0, name: 'MISSILE_COUNT', level: true},
    Ncs4: {type: 1, name: 'MAX_DAMAGE_NCS4', level: true},
    Ncs5: {type: 1, name: 'BUILDING_DAMAGE_FACTOR_NCS5', level: true},
    Ncs6: {type: 1, name: 'EFFECT_DURATION', level: true},
    Ndc1: {type: 3, name: 'RACE_TO_CONVERT', level: true, multiline: true},
    Ndc2: {type: 0, name: 'CONVERSION_UNIT', level: true},
    Nde1: {type: 1, name: 'CHANCE_TO_DEMOLISH', level: true},
    Nde2: {type: 1, name: 'DAMAGE_MULTIPLIER_BUILDINGS', level: true},
    Nde3: {type: 1, name: 'DAMAGE_MULTIPLIER_UNITS', level: true},
    Nde4: {type: 1, name: 'DAMAGE_MULTIPLIER_HEROES', level: true},
    Ndo1: {type: 1, name: 'DAMAGE_PER_SECOND_NDO1', level: true},
    Ndo2: {type: 0, name: 'NUMBER_OF_SUMMONED_UNITS_NDO2', level: true},
    Ndo3: {type: 1, name: 'SUMMONED_UNIT_DURATION_SECONDS_NDO3', level: true},
    Ndou: {type: 0, name: 'SUMMONED_UNIT_TYPE_NDOU', level: true},
    Ndp1: {type: 3, name: 'SPAWNED_UNITS', level: true, multiline: true},
    Ndp2: {type: 0, name: 'MINIMUM_NUMBER_OF_UNITS', level: true},
    Ndp3: {type: 0, name: 'MAXIMUM_NUMBER_OF_UNITS_NDP3', level: true},
    Ndr1: {type: 1, name: 'HIT_POINTS_DRAINED', level: true},
    Ndr2: {type: 1, name: 'MANA_POINTS_DRAINED', level: true},
    Ndr3: {type: 1, name: 'DRAIN_INTERVAL_SECONDS', level: true},
    Ndr4: {type: 1, name: 'LIFE_TRANSFERRED_PER_SECOND', level: true},
    Ndr5: {type: 1, name: 'MANA_TRANSFERRED_PER_SECOND', level: true},
    Ndr6: {type: 1, name: 'BONUS_LIFE_FACTOR', level: true},
    Ndr7: {type: 1, name: 'BONUS_LIFE_DECAY', level: true},
    Ndr8: {type: 1, name: 'BONUS_MANA_FACTOR', level: true},
    Ndr9: {type: 1, name: 'BONUS_MANA_DECAY', level: true},
    Ndt1: {type: 0, name: 'GOLD_COST_NDT1', level: true},
    Ndt2: {type: 0, name: 'LUMBER_COST_NDT2', level: true},
    Ndt3: {type: 0, name: 'DETECTION_TYPE_NDT3', level: true},
    Nef1: {type: 0, name: 'SUMMONED_UNIT_TYPES', level: true},
    Neg1: {type: 1, name: 'MOVE_SPEED_BONUS_NEG1', level: true},
    Neg2: {type: 1, name: 'DAMAGE_BONUS_NEG2', level: true},
    Neg3: {type: 3, name: 'ABILITY_UPGRADE_1', level: true, multiline: true},
    Neg4: {type: 3, name: 'ABILITY_UPGRADE_2', level: true, multiline: true},
    Neg5: {type: 3, name: 'ABILITY_UPGRADE_3', level: true, multiline: true},
    Neg6: {type: 3, name: 'ABILITY_UPGRADE_4', level: true, multiline: true},
    Neu1: {type: 1, name: 'ACTIVATION_RADIUS', level: true},
    Neu2: {type: 0, name: 'INTERACTION_TYPE', level: true},
    Neu3: {type: 0, name: 'SHOW_SELECT_UNIT_BUTTON (boolean)', level: true},
    Neu4: {type: 0, name: 'SHOW_UNIT_INDICATOR (boolean)', level: true},
    Nfd1: {type: 1, name: 'GRAPHIC_DELAY_NFD1', level: true},
    Nfd2: {type: 1, name: 'GRAPHIC_DURATION_NFD2', level: true},
    Nfd3: {type: 1, name: 'DAMAGE_NFD3', level: true},
    Nfy1: {type: 1, name: 'SPAWN_INTERVAL_NFY1', level: true},
    Nfy2: {type: 1, name: 'LEASH_RANGE_NFY2', level: true},
    Nfyu: {type: 0, name: 'SPAWN_UNIT_ID_NFYU', level: true},
    Nhs6: {type: 0, name: 'WAVE_COUNT_NHS6', level: true},
    Nic1: {type: 1, name: 'BONUS_DAMAGE_MULTIPLIER', level: true},
    Nic2: {type: 1, name: 'DEATH_DAMAGE_FULL_AMOUNT', level: true},
    Nic3: {type: 1, name: 'DEATH_DAMAGE_FULL_AREA', level: true},
    Nic4: {type: 1, name: 'DEATH_DAMAGE_HALF_AMOUNT', level: true},
    Nic5: {type: 1, name: 'DEATH_DAMAGE_HALF_AREA', level: true},
    Nic6: {type: 1, name: 'DEATH_DAMAGE_DELAY', level: true},
    Nlm2: {type: 1, name: 'SPLIT_DELAY', level: true},
    Nlm3: {type: 0, name: 'SPLIT_ATTACK_COUNT', level: true},
    Nlm4: {type: 1, name: 'MAX_HITPOINT_FACTOR', level: true},
    Nlm5: {type: 1, name: 'LIFE_DURATION_SPLIT_BONUS', level: true},
    Nlm6: {type: 0, name: 'GENERATION_COUNT', level: true},
    Nmr1: {type: 1, name: 'MANA_DRAINED_PER_SECOND_NMR1', level: true},
    Nms1: {type: 1, name: 'MANA_PER_HIT_POINT', level: true},
    Nms2: {type: 1, name: 'DAMAGE_ABSORBED_PERCENT', level: true},
    Npa5: {type: 0, name: 'SUMMONED_UNIT_COUNT_NPA5', level: true},
    Npa6: {type: 1, name: 'SUMMONED_UNIT_DURATION', level: true},
    Npr1: {type: 0, name: 'BUILDING_TYPES_ALLOWED_NPR1', level: true},
    Nrc1: {type: 3, name: 'ABILITY_FOR_UNIT_CREATION', level: true, multiline: true},
    Nrc2: {type: 0, name: 'NUMBER_OF_UNITS_CREATED_NRC2', level: true},
    Nrg5: {type: 0, name: 'STRENGTH_BONUS_NRG5', level: true},
    Nrg6: {type: 0, name: 'DEFENSE_BONUS_NRG6', level: true},
    Nsa1: {type: 0, name: 'BUILDING_TYPES_ALLOWED_NSA1', level: true},
    Nsa2: {type: 1, name: 'HERO_REGENERATION_DELAY', level: true},
    Nsa3: {type: 1, name: 'UNIT_REGENERATION_DELAY', level: true},
    Nsa4: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_NSA4', level: true},
    Nsa5: {type: 1, name: 'HIT_POINTS_PER_SECOND_NSA5', level: true},
    Nse1: {type: 1, name: 'SHIELD_COOLDOWN_TIME', level: true},
    Nsi1: {type: 0, name: 'ATTACKS_PREVENTED', level: true},
    Nsi2: {type: 1, name: 'CHANCE_TO_MISS_PERCENT', level: true},
    Nsi3: {type: 1, name: 'MOVEMENT_SPEED_MODIFIER', level: true},
    Nsi4: {type: 1, name: 'ATTACK_SPEED_MODIFIER', level: true},
    Nsl1: {type: 0, name: 'UNIT_TO_PRESERVE', level: true},
    Nso1: {type: 1, name: 'DAMAGE_AMOUNT_NSO1', level: true},
    Nso2: {type: 1, name: 'DAMAGE_PERIOD', level: true},
    Nso3: {type: 1, name: 'DAMAGE_PENALTY', level: true},
    Nso4: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_PERCENT_NSO4', level: true},
    Nso5: {type: 1, name: 'ATTACK_SPEED_REDUCTION_PERCENT_NSO5', level: true},
    Nsp1: {type: 0, name: 'GOLD_COST_PER_STRUCTURE', level: true},
    Nsp2: {type: 0, name: 'LUMBER_COST_PER_USE', level: true},
    Nsp3: {type: 0, name: 'DETECTION_TYPE_NSP3', level: true},
    Nst1: {type: 0, name: 'BEASTS_PER_SECOND', level: true},
    Nst2: {type: 1, name: 'BEAST_COLLISION_RADIUS', level: true},
    Nst3: {type: 1, name: 'DAMAGE_AMOUNT_NST3', level: true},
    Nst4: {type: 1, name: 'DAMAGE_RADIUS', level: true},
    Nst5: {type: 1, name: 'DAMAGE_DELAY', level: true},
    Nsy1: {type: 1, name: 'SPAWN_INTERVAL_NSY1', level: true},
    Nsy2: {type: 3, name: 'SPAWN_UNIT_ID_NSY2', level: true, multiline: true},
    Nsy3: {type: 1, name: 'SPAWN_UNIT_DURATION', level: true},
    Nsy4: {type: 1, name: 'SPAWN_UNIT_OFFSET', level: true},
    Nsy5: {type: 1, name: 'LEASH_RANGE_NSY5', level: true},
    Nsyu: {type: 0, name: 'FACTORY_UNIT_ID', level: true},
    Ntm1: {type: 1, name: 'GOLD_COST_FACTOR', level: true},
    Ntm2: {type: 1, name: 'LUMBER_COST_FACTOR', level: true},
    Ntm3: {type: 0, name: 'MAX_CREEP_LEVEL_NTM3', level: true},
    Ntm4: {type: 0, name: 'ALLOW_BOUNTY (boolean)', level: true},
    Ntou: {type: 0, name: 'SUMMONED_UNIT_TYPE_NTOU', level: true},
    Nvc1: {type: 0, name: 'ROCK_RING_COUNT', level: true},
    Nvc2: {type: 0, name: 'WAVE_COUNT_NVC2', level: true},
    Nvc3: {type: 1, name: 'WAVE_INTERVAL', level: true},
    Nvc4: {type: 1, name: 'BUILDING_DAMAGE_FACTOR_NVC4', level: true},
    Nvc5: {type: 1, name: 'FULL_DAMAGE_AMOUNT_NVC5', level: true},
    Nvc6: {type: 1, name: 'HALF_DAMAGE_FACTOR', level: true},
    Nvcu: {type: 0, name: 'DESTRUCTIBLE_ID', level: true},
    Oae1: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_PERCENT_OAE1', level: true},
    Oae2: {type: 1, name: 'ATTACK_SPEED_INCREASE_PERCENT_OAE2', level: true},
    Oar1: {type: 1, name: 'AMOUNT_OF_HIT_POINTS_REGENERATED', level: true},
    Oar2: {type: 0, name: 'PERCENTAGE_OAR2 (boolean)', level: true},
    Ocl1: {type: 1, name: 'DAMAGE_PER_TARGET_OCL1', level: true},
    Ocl2: {type: 0, name: 'NUMBER_OF_TARGETS_HIT', level: true},
    Ocl3: {type: 1, name: 'DAMAGE_REDUCTION_PER_TARGET', level: true},
    Ocr1: {type: 1, name: 'CHANCE_TO_CRITICAL_STRIKE', level: true},
    Ocr2: {type: 1, name: 'DAMAGE_MULTIPLIER_OCR2', level: true},
    Ocr3: {type: 1, name: 'DAMAGE_BONUS_OCR3', level: true},
    Ocr4: {type: 1, name: 'CHANCE_TO_EVADE_OCR4', level: true},
    Ocr5: {type: 0, name: 'NEVER_MISS_OCR5 (boolean)', level: true},
    Ocr6: {type: 0, name: 'EXCLUDE_ITEM_DAMAGE (boolean)', level: true},
    Oeq1: {type: 1, name: 'EFFECT_DELAY_OEQ1', level: true},
    Oeq2: {type: 1, name: 'DAMAGE_PER_SECOND_TO_BUILDINGS', level: true},
    Oeq3: {type: 1, name: 'UNITS_SLOWED_PERCENT', level: true},
    Oeq4: {type: 1, name: 'FINAL_AREA_OEQ4', level: true},
    Ofs1: {type: 0, name: 'DETECTION_TYPE_OFS1', level: true},
    Omi1: {type: 0, name: 'NUMBER_OF_IMAGES', level: true},
    Omi2: {type: 1, name: 'DAMAGE_DEALT_PERCENT_OMI2', level: true},
    Omi3: {type: 1, name: 'DAMAGE_TAKEN_PERCENT_OMI3', level: true},
    Omi4: {type: 1, name: 'ANIMATION_DELAY', level: true},
    Ore1: {type: 1, name: 'REINCARNATION_DELAY', level: true},
    Osf1: {type: 0, name: 'SUMMONED_UNIT_OSF1', level: true},
    Osf2: {type: 0, name: 'NUMBER_OF_SUMMONED_UNITS_OSF2', level: true},
    Osh1: {type: 1, name: 'DAMAGE_OSH1', level: true},
    Osh2: {type: 1, name: 'MAXIMUM_DAMAGE_OSH2', level: true},
    Osh3: {type: 1, name: 'DISTANCE_OSH3', level: true},
    Osh4: {type: 1, name: 'FINAL_AREA_OSH4', level: true},
    Owk1: {type: 1, name: 'TRANSITION_TIME', level: true},
    Owk2: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_PERCENT_OWK2', level: true},
    Owk3: {type: 1, name: 'BACKSTAB_DAMAGE', level: true},
    Owk4: {type: 0, name: 'BACKSTAB_DAMAGE (boolean)', level: true},
    Oww1: {type: 1, name: 'DAMAGE_PER_SECOND_OWW1', level: true},
    Oww2: {type: 1, name: 'MAGIC_DAMAGE_REDUCTION_OWW2', level: true},
    Ply1: {type: 0, name: 'MAXIMUM_CREEP_LEVEL_PLY1', level: true},
    Ply2: {type: 3, name: 'MORPH_UNITS_GROUND', level: true, multiline: true},
    Ply3: {type: 3, name: 'MORPH_UNITS_AIR', level: true, multiline: true},
    Ply4: {type: 3, name: 'MORPH_UNITS_AMPHIBIOUS', level: true, multiline: true},
    Ply5: {type: 3, name: 'MORPH_UNITS_WATER', level: true, multiline: true},
    Poa1: {type: 1, name: 'EXTRA_DAMAGE_POA1', level: true},
    Poa2: {type: 1, name: 'DAMAGE_PER_SECOND_POA2', level: true},
    Poa3: {type: 1, name: 'ATTACK_SPEED_FACTOR_POA3', level: true},
    Poa4: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_POA4', level: true},
    Poa5: {type: 0, name: 'STACKING_TYPE_POA5', level: true},
    Poi1: {type: 1, name: 'DAMAGE_PER_SECOND_POI1', level: true},
    Poi2: {type: 1, name: 'ATTACK_SPEED_FACTOR_POI2', level: true},
    Poi3: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_POI3', level: true},
    Poi4: {type: 0, name: 'STACKING_TYPE_POI4', level: true},
    Pos1: {type: 0, name: 'MAXIMUM_CREEP_LEVEL_POS1', level: true},
    Pos2: {type: 1, name: 'DAMAGE_AMPLIFICATION', level: true},
    Pos3: {type: 0, name: 'TARGET_IS_INVULNERABLE (boolean)', level: true},
    Pos4: {type: 0, name: 'TARGET_IS_MAGIC_IMMUNE (boolean)', level: true},
    Prg1: {type: 0, name: 'MOVEMENT_UPDATE_FREQUENCY_PRG1', level: true},
    Prg2: {type: 0, name: 'ATTACK_UPDATE_FREQUENCY_PRG2', level: true},
    Prg3: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_PRG3', level: true},
    Prg4: {type: 1, name: 'UNIT_PAUSE_DURATION', level: true},
    Prg5: {type: 1, name: 'HERO_PAUSE_DURATION', level: true},
    Prg6: {type: 0, name: 'MANA_LOSS_PRG6', level: true},
    Rai1: {type: 0, name: 'UNITS_SUMMONED_TYPE_ONE', level: true},
    Rai2: {type: 0, name: 'UNITS_SUMMONED_TYPE_TWO', level: true},
    Rai3: {type: 3, name: 'UNIT_TYPE_ONE', level: true, multiline: true},
    Rai4: {type: 3, name: 'UNIT_TYPE_TWO', level: true, multiline: true},
    Raiu: {type: 0, name: 'UNIT_TYPE_FOR_LIMIT_CHECK', level: true},
    Rej1: {type: 1, name: 'HIT_POINTS_GAINED_REJ1', level: true},
    Rej2: {type: 1, name: 'MANA_POINTS_GAINED_REJ2', level: true},
    Rej3: {type: 0, name: 'ALLOW_WHEN_FULL_REJ3', level: true},
    Rej4: {type: 0, name: 'NO_TARGET_REQUIRED_REJ4 (boolean)', level: true},
    Rep1: {type: 1, name: 'REPAIR_COST_RATIO', level: true},
    Rep2: {type: 1, name: 'REPAIR_TIME_RATIO', level: true},
    Rep3: {type: 1, name: 'POWERBUILD_COST', level: true},
    Rep4: {type: 1, name: 'POWERBUILD_RATE', level: true},
    Rep5: {type: 1, name: 'NAVAL_RANGE_BONUS', level: true},
    Roa1: {type: 1, name: 'DAMAGE_INCREASE_PERCENT_ROA1', level: true},
    Roa2: {type: 0, name: 'DEFENSE_INCREASE_ROA2', level: true},
    Roa3: {type: 1, name: 'LIFE_REGENERATION_RATE', level: true},
    Roa4: {type: 1, name: 'MANA_REGEN', level: true},
    Roa5: {type: 0, name: 'PREFER_HOSTILES_ROA5 (boolean)', level: true},
    Roa6: {type: 0, name: 'PREFER_FRIENDLIES_ROA6 (boolean)', level: true},
    Roa7: {type: 0, name: 'MAX_UNITS_ROA7', level: true},
    Roo1: {type: 0, name: 'ROOTED_WEAPONS', level: true},
    Roo2: {type: 0, name: 'UPROOTED_WEAPONS', level: true},
    Roo3: {type: 0, name: 'ROOTED_TURNING (boolean)', level: true},
    Roo4: {type: 0, name: 'UPROOTED_DEFENSE_TYPE', level: true},
    Rpb3: {type: 1, name: 'MINIMUM_LIFE_REQUIRED', level: true},
    Rpb4: {type: 1, name: 'MINIMUM_MANA_REQUIRED', level: true},
    Rpb5: {type: 0, name: 'MAXIMUM_UNITS_CHARGED_TO_CASTER', level: true},
    Rpb6: {type: 0, name: 'MAXIMUM_UNITS_AFFECTED', level: true},
    Rtn1: {type: 0, name: 'ACCEPTS_GOLD (boolean)', level: true},
    Rtn2: {type: 0, name: 'ACCEPTS_LUMBER (boolean)', level: true},
    Sal1: {type: 1, name: 'SALVAGE_COST_RATIO', level: true},
    Sal2: {type: 0, name: 'ACCUMULATION_STEP', level: true},
    Sds1: {type: 1, name: 'BUILDING_DAMAGE_FACTOR_SDS1', level: true},
    Sds6: {type: 0, name: 'EXPLODES_ON_DEATH (boolean)', level: true},
    Shm1: {type: 1, name: 'FADE_DURATION', level: true},
    Shm2: {type: 1, name: 'DAY_NIGHT_DURATION', level: true},
    Shm3: {type: 1, name: 'ACTION_DURATION', level: true},
    Slo1: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_SLO1', level: true},
    Slo2: {type: 1, name: 'ATTACK_SPEED_FACTOR_SLO2', level: true},
    Slo3: {type: 0, name: 'ALWAYS_AUTOCAST_SLO3 (boolean)', level: true},
    Sod1: {type: 0, name: 'NUMBER_OF_UNITS', level: true},
    Sod2: {type: 3, name: 'UNIT_TYPE_SOD2', level: true, multiline: true},
    Spa1: {type: 0, name: 'SPIDER_CAPACITY', level: true},
    Spo1: {type: 1, name: 'DAMAGE_PER_SECOND_SPO1', level: true},
    Spo2: {type: 1, name: 'MOVEMENT_SPEED_FACTOR_SPO2', level: true},
    Spo3: {type: 1, name: 'ATTACK_SPEED_FACTOR_SPO3', level: true},
    Spo4: {type: 0, name: 'STACKING_TYPE_SPO4', level: true},
    Ssk1: {type: 1, name: 'CHANCE_TO_REDUCE_DAMAGE_PERCENT', level: true},
    Ssk2: {type: 1, name: 'MINIMUM_DAMAGE', level: true},
    Ssk3: {type: 1, name: 'IGNORED_DAMAGE', level: true},
    Ssk4: {type: 0, name: 'INCLUDE_RANGED_DAMAGE (boolean)', level: true},
    Ssk5: {type: 0, name: 'INCLUDE_MELEE_DAMAGE (boolean)', level: true},
    Sta1: {type: 1, name: 'ACTIVATION_DELAY_STA1', level: true},
    Sta2: {type: 1, name: 'DETECTION_RADIUS_STA2', level: true},
    Sta3: {type: 1, name: 'DETONATION_RADIUS', level: true},
    Sta4: {type: 1, name: 'STUN_DURATION_STA4', level: true},
    Stau: {type: 0, name: 'WARD_UNIT_TYPE_STAU', level: true},
    Tau1: {type: 0, name: 'PREFER_HOSTILES_TAU1', level: true},
    Tau2: {type: 0, name: 'PREFER_FRIENDLIES_TAU2', level: true},
    Tau3: {type: 0, name: 'MAX_UNITS_TAU3', level: true},
    Tau4: {type: 0, name: 'NUMBER_OF_PULSES', level: true},
    Tau5: {type: 1, name: 'INTERVAL_BETWEEN_PULSES', level: true},
    Tdg1: {type: 1, name: 'DAMAGE_PER_SECOND_TDG1', level: true},
    Tdg2: {type: 1, name: 'MEDIUM_DAMAGE_RADIUS_TDG2', level: true},
    Tdg3: {type: 1, name: 'MEDIUM_DAMAGE_PER_SECOND', level: true},
    Tdg4: {type: 1, name: 'SMALL_DAMAGE_RADIUS_TDG4', level: true},
    Tdg5: {type: 1, name: 'SMALL_DAMAGE_PER_SECOND', level: true},
    Tsp1: {type: 1, name: 'AIR_TIME_SECONDS_TSP1', level: true},
    Tsp2: {type: 1, name: 'MINIMUM_HIT_INTERVAL_SECONDS', level: true},
    Uan1: {type: 0, name: 'NUMBER_OF_CORPSES_RAISED_UAN1', level: true},
    Uan3: {type: 0, name: 'INHERIT_UPGRADES_UAN3 (boolean)', level: true},
    Uau1: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_PERCENT_UAU1', level: true},
    Uau2: {type: 1, name: 'LIFE_REGENERATION_INCREASE_PERCENT', level: true},
    Uau3: {type: 0, name: 'PERCENT_BONUS_UAU3 (boolean)', level: true},
    Uav1: {type: 1, name: 'ATTACK_DAMAGE_STOLEN_PERCENT', level: true},
    Ucb5: {type: 0, name: 'MAX_UNITS_SUMMONED', level: true},
    Ucb6: {type: 0, name: 'KILL_ON_CASTER_DEATH (boolean)', level: true},
    Uco5: {type: 1, name: 'MAX_DAMAGE_UCO5', level: true},
    Uco6: {type: 1, name: 'MOVE_SPEED_BONUS_UCO6', level: true},
    Ucs1: {type: 1, name: 'DAMAGE_UCS1', level: true},
    Ucs2: {type: 1, name: 'MAX_DAMAGE_UCS2', level: true},
    Ucs3: {type: 1, name: 'DISTANCE_UCS3', level: true},
    Ucs4: {type: 1, name: 'FINAL_AREA_UCS4', level: true},
    Udc1: {type: 1, name: 'AMOUNT_HEALED_DAMAGED_UDC1', level: true},
    Udd1: {type: 1, name: 'MAX_LIFE_DRAINED_PER_SECOND_PERCENT', level: true},
    Udd2: {type: 1, name: 'BUILDING_REDUCTION_UDD2', level: true},
    Udp1: {type: 1, name: 'LIFE_CONVERTED_TO_MANA', level: true},
    Udp2: {type: 1, name: 'LIFE_CONVERTED_TO_LIFE', level: true},
    Udp3: {type: 0, name: 'MANA_CONVERSION_AS_PERCENT (boolean)', level: true},
    Udp4: {type: 0, name: 'LIFE_CONVERSION_AS_PERCENT (boolean)', level: true},
    Udp5: {type: 0, name: 'LEAVE_TARGET_ALIVE (boolean)', level: true},
    Uds1: {type: 0, name: 'MAXIMUM_UNITS', level: true},
    Uds2: {type: 1, name: 'CASTING_DELAY_SECONDS', level: true},
    Ufa1: {type: 1, name: 'ARMOR_DURATION', level: true},
    Ufa2: {type: 1, name: 'ARMOR_BONUS_UFA2', level: true},
    Ufn1: {type: 1, name: 'AREA_OF_EFFECT_DAMAGE', level: true},
    Ufn2: {type: 1, name: 'SPECIFIC_TARGET_DAMAGE_UFN2', level: true},
    Uhf1: {type: 1, name: 'ATTACK_SPEED_BONUS_PERCENT', level: true},
    Uhf2: {type: 1, name: 'DAMAGE_PER_SECOND_UHF2', level: true},
    Uim1: {type: 1, name: 'WAVE_DISTANCE', level: true},
    Uim2: {type: 1, name: 'WAVE_TIME_SECONDS', level: true},
    Uim3: {type: 1, name: 'DAMAGE_DEALT_UIM3', level: true},
    Uim4: {type: 1, name: 'AIR_TIME_SECONDS_UIM4', level: true},
    Uin1: {type: 1, name: 'DAMAGE_UIN1', level: true},
    Uin2: {type: 1, name: 'DURATION', level: true},
    Uin3: {type: 1, name: 'IMPACT_DELAY', level: true},
    Uin4: {type: 0, name: 'SUMMONED_UNIT_UIN4', level: true},
    Uls1: {type: 0, name: 'NUMBER_OF_SWARM_UNITS', level: true},
    Uls2: {type: 1, name: 'UNIT_RELEASE_INTERVAL_SECONDS', level: true},
    Uls3: {type: 0, name: 'MAX_SWARM_UNITS_PER_TARGET', level: true},
    Uls4: {type: 1, name: 'DAMAGE_RETURN_FACTOR', level: true},
    Uls5: {type: 1, name: 'DAMAGE_RETURN_THRESHOLD', level: true},
    Ulsu: {type: 0, name: 'SWARM_UNIT_TYPE', level: true},
    Usl1: {type: 1, name: 'STUN_DURATION_USL1', level: true},
    Uts1: {type: 1, name: 'RETURNED_DAMAGE_FACTOR', level: true},
    Uts2: {type: 1, name: 'RECEIVED_DAMAGE_FACTOR', level: true},
    Uts3: {type: 1, name: 'DEFENSE_BONUS_UTS3', level: true},
    War1: {type: 1, name: 'CHANCE_TO_STOMP_PERCENT', level: true},
    War2: {type: 1, name: 'DAMAGE_DEALT_WAR2', level: true},
    War3: {type: 1, name: 'FULL_DAMAGE_RADIUS_WAR3', level: true},
    War4: {type: 1, name: 'HALF_DAMAGE_RADIUS_WAR4', level: true},
    Wha1: {type: 1, name: 'LUMBER_PER_INTERVAL', level: true},
    Wha2: {type: 0, name: 'INTERVALS_BEFORE_CHANGING_TREES', level: true},
    Wha3: {type: 1, name: 'ART_ATTACHMENT_HEIGHT', level: true},
    Wrp1: {type: 1, name: 'TELEPORT_AREA_WIDTH', level: true},
    Wrp2: {type: 1, name: 'TELEPORT_AREA_HEIGHT', level: true},
    Wrs1: {type: 1, name: 'DAMAGE_WRS1', level: true},
    Wrs2: {type: 1, name: 'TERRAIN_DEFORMATION_AMPLITUDE', level: true},
    Wrs3: {type: 0, name: 'TERRAIN_DEFORMATION_DURATION_MS', level: true},
    aaea: {type: 3, name: 'AREA_EFFECT', level: true, multiline: true},
    aare: {type: 1, name: 'AREA_OF_EFFECT', level: true},
    aart: {type: 3, name: 'ICON_NORMAL', multiline: true},
    //aart: {type: 3, name: 'ICON_NORMAL', level: true, multiline: true},
    abpx: {type: 0, name: 'BUTTON_POSITION_NORMAL_X'},
    abpy: {type: 0, name: 'BUTTON_POSITION_NORMAL_Y'},
    abs1: {type: 1, name: 'MAXIMUM_LIFE_ABSORBED', level: true},
    abs2: {type: 1, name: 'MAXIMUM_MANA_ABSORBED', level: true},
    acac: {type: 0, name: 'CASTER_ATTACHMENTS'},
    acas: {type: 1, name: 'CASTING_TIME', level: true},
    acat: {type: 3, name: 'CASTER', level: true, multiline: true},
    acbs: {type: 1, name: 'CAST_BACK_SWING', level: true},
    acdn: {type: 1, name: 'COOLDOWN', level: true},
    achd: {type: 0, name: 'CHECK_DEPENDENCIES (boolean)'},
    acpt: {type: 1, name: 'CAST_POINT', level: true},
    adur: {type: 1, name: 'DURATION_NORMAL', level: true},
    aeat: {type: 3, name: 'EFFECT', level: true, multiline: true},
    aefl: {type: 3, name: 'EFFECT_SOUND_LOOPING', multiline: true},
    aefs: {type: 3, name: 'EFFECT_SOUND', multiline: true},
    ahdu: {type: 1, name: 'DURATION_HERO', level: true},
    aher: {type: 0, name: 'HERO_ABILITY (boolean)'},
    ahky: {type: 0, name: 'BUTTON_HOTKEY_NORMAL'},
    ahtk: {type: 0, name: 'BUTTON_HOTKEY_ALL'},
    aite: {type: 0, name: 'ITEM_ABILITY (boolean)'},
    alev: {type: 0, name: 'LEVELS'},
    alig: {type: 3, name: 'LIGHTNING_EFFECTS', level: true, multiline: true},
    alsk: {type: 0, name: 'LEVEL_SKIP_REQUIREMENT'},
    amac: {type: 1, name: 'ARF_MISSILE_ARC'},
    amat: {type: 3, name: 'MISSILE_ART', level: true, multiline: true},
    amcs: {type: 0, name: 'MANA_COST', level: true},
    amho: {type: 0, name: 'HOMING (boolean)'},
    amsp: {type: 0, name: 'MISSILE_SPEED'},
    anam: {type: 3, name: 'NAME', multiline: true},
    apri: {type: 0, name: 'PRIORITY'},
    aran: {type: 1, name: 'CAST_RANGE', level: true},
    arar: {type: 3, name: 'ICON_RESEARCH', multiline: true},
    aret: {type: 3, name: 'TOOLTIP_LEARN', level: true, multiline: true},
    arlv: {type: 0, name: 'REQUIRED_LEVEL'},
    arpx: {type: 0, name: 'BUTTON_POSITION_RESEARCH_X'},
    arpy: {type: 0, name: 'BUTTON_POSITION_RESEARCH_Y'},
    artm: {type: 1, name: 'AURA_REFRESH_TIME'},
    arut: {type: 3, name: 'TOOLTIP_LEARN_EXTENDED', level: true, multiline: true},
    asat: {type: 3, name: 'SPECIAL', level: true, multiline: true},
    ast1: {type: 1, name: 'LIFE_RESTORED_FACTOR', level: true},
    ast2: {type: 1, name: 'MANA_RESTORED_FACTOR', level: true},
    atac: {type: 0, name: 'TARGET_ATTACHMENTS'},
    atar: {type: 0, name: 'TARGETS_ALLOWED', level: true},
    atat: {type: 3, name: 'TARGET', level: true, multiline: true},
    atp1: {type: 3, name: 'TOOLTIP_NORMAL', level: true, multiline: true},
    auar: {type: 3, name: 'ICON_ACTIVATED', multiline: true},
    aub1: {type: 3, name: 'TOOLTIP_NORMAL_EXTENDED', level: true, multiline: true},
    aubx: {type: 0, name: 'BUTTON_POSITION_ACTIVATED_X'},
    auby: {type: 0, name: 'BUTTON_POSITION_ACTIVATED_Y'},
    auhk: {type: 0, name: 'BUTTON_HOTKEY_ACTIVATED'},
    auhr: {type: 0, name: 'BUTTON_HOTKEY_RESEARCH'},
    aut1: {type: 3, name: 'TOOLTIP_TURN_OFF', level: true, multiline: true},
    auu1: {type: 3, name: 'TOOLTIP_TURN_OFF_EXTENDED', level: true, multiline: true},
    ave5: {type: 1, name: 'LIFE_REGENERATION_RATE_PER_SECOND', level: true},
    bsk1: {type: 1, name: 'MOVEMENT_SPEED_INCREASE_BSK1', level: true},
    bsk2: {type: 1, name: 'ATTACK_SPEED_INCREASE_BSK2', level: true},
    bsk3: {type: 1, name: 'DAMAGE_TAKEN_INCREASE', level: true},
    coa1: {type: 3, name: 'PARTNER_UNIT_TYPE', level: true, multiline: true},
    coa2: {type: 0, name: 'MOVE_TO_PARTNER (boolean)', level: true},
    coau: {type: 0, name: 'RESULTING_UNIT_TYPE_COAU', level: true},
    cyc1: {type: 0, name: 'CAN_BE_DISPELLED (boolean)', level: true},
    dcp1: {type: 3, name: 'PARTNER_UNIT_TYPE_ONE', level: true, multiline: true},
    dcp2: {type: 3, name: 'PARTNER_UNIT_TYPE_TWO', level: true, multiline: true},
    dvm1: {type: 1, name: 'LIFE_PER_UNIT', level: true},
    dvm2: {type: 1, name: 'MANA_PER_UNIT', level: true},
    dvm3: {type: 1, name: 'LIFE_PER_BUFF', level: true},
    dvm4: {type: 1, name: 'MANA_PER_BUFF', level: true},
    dvm5: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_DVM5', level: true},
    dvm6: {type: 0, name: 'IGNORE_FRIENDLY_BUFFS (boolean)', level: true},
    ent1: {type: 0, name: 'RESULTING_UNIT_TYPE_ENT1', level: true},
    exh1: {type: 0, name: 'MAXIMUM_NUMBER_OF_CORPSES_EXH1', level: true},
    exhu: {type: 0, name: 'UNIT_TYPE_EXHU', level: true},
    fak1: {type: 1, name: 'DAMAGE_BONUS_FAK1', level: true},
    fak2: {type: 1, name: 'MEDIUM_DAMAGE_FACTOR_FAK2', level: true},
    fak3: {type: 1, name: 'SMALL_DAMAGE_FACTOR_FAK3', level: true},
    fak4: {type: 1, name: 'FULL_DAMAGE_RADIUS_FAK4', level: true},
    fak5: {type: 1, name: 'HALF_DAMAGE_RADIUS_FAK5', level: true},
    fbk1: {type: 1, name: 'MAX_MANA_DRAINED_UNITS', level: true},
    fbk2: {type: 1, name: 'DAMAGE_RATIO_UNITS_PERCENT', level: true},
    fbk3: {type: 1, name: 'MAX_MANA_DRAINED_HEROS', level: true},
    fbk4: {type: 1, name: 'DAMAGE_RATIO_HEROS_PERCENT', level: true},
    fbk5: {type: 1, name: 'SUMMONED_DAMAGE', level: true},
    flk1: {type: 1, name: 'MEDIUM_DAMAGE_RADIUS_FLK1', level: true},
    flk2: {type: 1, name: 'SMALL_DAMAGE_RADIUS_FLK2', level: true},
    flk3: {type: 1, name: 'FULL_DAMAGE_AMOUNT_FLK3', level: true},
    flk4: {type: 1, name: 'MEDIUM_DAMAGE_AMOUNT', level: true},
    flk5: {type: 1, name: 'SMALL_DAMAGE_AMOUNT', level: true},
    gra1: {type: 1, name: 'ATTACH_DELAY', level: true},
    gra2: {type: 1, name: 'REMOVE_DELAY', level: true},
    gra3: {type: 0, name: 'DISABLED_ATTACK_INDEX', level: true},
    gra4: {type: 0, name: 'ENABLED_ATTACK_INDEX_GRA4', level: true},
    gra5: {type: 0, name: 'MAXIMUM_ATTACKS', level: true},
    hwdu: {type: 0, name: 'WARD_UNIT_TYPE_HWDU', level: true},
    ict1: {type: 0, name: 'NEW_TIME_OF_DAY_HOUR', level: true},
    ict2: {type: 0, name: 'NEW_TIME_OF_DAY_MINUTE', level: true},
    idc1: {type: 1, name: 'MANA_LOSS_PER_UNIT_IDC1', level: true},
    idc2: {type: 1, name: 'SUMMONED_UNIT_DAMAGE_IDC2', level: true},
    idc3: {type: 0, name: 'MAXIMUM_DISPELLED_UNITS', level: true},
    imo1: {type: 0, name: 'NUMBER_OF_LURES', level: true},
    imo2: {type: 1, name: 'ACTIVATION_DELAY_IMO2', level: true},
    imo3: {type: 1, name: 'LURE_INTERVAL_SECONDS', level: true},
    imou: {type: 0, name: 'LURE_UNIT_TYPE', level: true},
    inv1: {type: 0, name: 'ITEM_CAPACITY', level: true},
    inv2: {type: 0, name: 'DROP_ITEMS_ON_DEATH (boolean)', level: true},
    inv3: {type: 0, name: 'CAN_USE_ITEMS (boolean)', level: true},
    inv4: {type: 0, name: 'CAN_GET_ITEMS (boolean)', level: true},
    inv5: {type: 0, name: 'CAN_DROP_ITEMS (boolean)', level: true},
    ipmu: {type: 0, name: 'UNIT_TYPE_IPMU', level: true},
    ipv1: {type: 1, name: 'DAMAGE_BONUS_IPV1', level: true},
    ipv2: {type: 1, name: 'LIFE_STEAL_AMOUNT', level: true},
    ipv3: {type: 0, name: 'AMOUNT_IS_RAW_VALUE (boolean)', level: true},
    irc2: {type: 0, name: 'RESTORED_LIFE', level: true},
    irc3: {type: 0, name: 'RESTORED_MANA__1_FOR_CURRENT', level: true},
    irl1: {type: 1, name: 'LIFE_REGENERATED', level: true},
    irl2: {type: 1, name: 'MANA_REGENERATED', level: true},
    irl3: {type: 0, name: 'ALLOW_WHEN_FULL_IRL3', level: true},
    irl4: {type: 0, name: 'NO_TARGET_REQUIRED_IRL4 (boolean)', level: true},
    irl5: {type: 0, name: 'DISPEL_ON_ATTACK (boolean)', level: true},
    isr1: {type: 1, name: 'DAMAGE_BONUS_ISR1', level: true},
    isr2: {type: 1, name: 'DAMAGE_REDUCTION_ISR2', level: true},
    liq1: {type: 1, name: 'EXTRA_DAMAGE_PER_SECOND', level: true},
    liq2: {type: 1, name: 'MOVEMENT_SPEED_REDUCTION_LIQ2', level: true},
    liq3: {type: 1, name: 'ATTACK_SPEED_REDUCTION_LIQ3', level: true},
    liq4: {type: 0, name: 'REPAIRS_ALLOWED (boolean)', level: true},
    mec1: {type: 0, name: 'NUMBER_OF_UNITS_CREATED_MEC1', level: true},
    mfl1: {type: 1, name: 'UNIT_DAMAGE_PER_MANA_POINT', level: true},
    mfl2: {type: 1, name: 'HERO_DAMAGE_PER_MANA_POINT', level: true},
    mfl3: {type: 1, name: 'UNIT_MAXIMUM_DAMAGE', level: true},
    mfl4: {type: 1, name: 'HERO_MAXIMUM_DAMAGE', level: true},
    mfl5: {type: 1, name: 'DAMAGE_COOLDOWN', level: true},
    mfl6: {type: 0, name: 'CASTER_ONLY_SPLASH (boolean)', level: true},
    mim1: {type: 1, name: 'MAGIC_DAMAGE_FACTOR', level: true},
    mls1: {type: 1, name: 'DAMAGE_PER_SECOND_MLS1', level: true},
    nca1: {type: 1, name: 'DISTRIBUTED_DAMAGE_FACTOR_NCA1', level: true},
    pxf1: {type: 1, name: 'INITIAL_DAMAGE_PXF1', level: true},
    pxf2: {type: 1, name: 'DAMAGE_PER_SECOND_PXF2', level: true},
    sla1: {type: 0, name: 'SLEEP_ONCE (boolean)', level: true},
    sla2: {type: 0, name: 'ALLOW_ON_ANY_PLAYER_SLOT (boolean)', level: true},
    spb1: {type: 3, name: 'SPELL_LIST', level: true, multiline: true},
    spb2: {type: 0, name: 'SHARED_SPELL_COOLDOWN (boolean)', level: true},
    spb3: {type: 0, name: 'MINIMUM_SPELLS', level: true},
    spb4: {type: 0, name: 'MAXIMUM_SPELLS', level: true},
    spb5: {type: 3, name: 'BASE_ORDER_ID_SPB5', level: true, multiline: true},
    spl1: {type: 1, name: 'DISTRIBUTED_DAMAGE_FACTOR_SPL1', level: true},
    spl2: {type: 0, name: 'MAXIMUM_NUMBER_OF_TARGETS_SPL2', level: true},
    tpi1: {type: 3, name: 'REQUIRED_UNIT_TYPE', level: true, multiline: true},
    tpi2: {type: 3, name: 'CONVERTED_UNIT_TYPE', level: true, multiline: true},
};
export default map;
