[Settings]
version = 3 # binary format version

[Udre] # 1432646245 0x55647265
# (abilCode) auto : Default Active Ability
udaaType = "string"
udaa = "AOr2"
# (heroAbilityList) heroAbilList : Hero
uhabType = "string"
uhab = "AUsl,AUcs,AUin"
# (abilityList) abilList : Normal
uabiType = "string"
uabi = "Agyb,AInv"
# (unreal) castbsw : Animation - Cast Backswing
ucbsType = "unreal"
ucbs = 1.63
# (unreal) castpt : Animation - Cast Point
ucptType = "unreal"
ucpt = 0.4
# (real) run : Animation - Run Speed
urunType = "real"
urun = 290.1
# (real) walk : Animation - Walk Speed
uwalType = "real"
uwal = 290.1
# (unreal) death : Death Time (seconds)
udtmType = "unreal"
udtm = 3.1
# (unreal) occH : Occluder Height
uoccType = "unreal"
uocc = 0.1
# (int) orientInterp : Orientation Interpolation
uoriType = "integer"
uori = 5
# (unreal) propWin : Propulsion Window (degrees)
uprwType = "unreal"
uprw = 60.1
# (teamColor) teamColor : Team Color
utcoType = "integer"
utco = 2
# (bool) fatLOS : Use Extended Line of Sight
ulosType = "integer"
ulos = 1
# (unreal) acquire : Acquisition Range
uacqType = "unreal"
uacq = 499.8
# (armorType) armor : Armor Type
uarmType = "string"
uarm = "Ethereal"
# (unreal) backSw1 : Attack 1 - Animation Backswing Point
ubs1Type = "unreal"
ubs1 = 0.65
# (unreal) dmgpt1 : Attack 1 - Animation Damage Point
udp1Type = "unreal"
udp1 = 0.65
# (int) Farea1 : Attack 1 - Area of Effect (Full Damage)
ua1fType = "integer"
ua1f = 1
# (int) Harea1 : Attack 1 - Area of Effect (Medium Damage)
ua1hType = "integer"
ua1h = 1
# (int) Qarea1 : Attack 1 - Area of Effect (Small Damage)
ua1qType = "integer"
ua1q = 1
# (targetList) splashTargs1 : Attack 1 - Area of Effect Targets
ua1pType = "string"
ua1p = "air,alive"
# (attackType) atkType1 : Attack 1 - Attack Type
ua1tType = "string"
ua1t = "normal"
# (unreal) cool1 : Attack 1 - Cooldown Time
ua1cType = "unreal"
ua1c = 1.9
# (int) dmgplus1 : Attack 1 - Damage Base
ua1bType = "integer"
ua1b = 1
# (unreal) Hfact1 : Attack 1 - Damage Factor - Medium
uhd1Type = "unreal"
uhd1 = 0.1
# (unreal) Qfact1 : Attack 1 - Damage Factor - Small
uqd1Type = "unreal"
uqd1 = 0.1
# (unreal) damageLoss1 : Attack 1 - Damage Loss Factor
udl1Type = "unreal"
udl1 = 0.1
# (int) dice1 : Attack 1 - Damage Number of Dice
ua1dType = "integer"
ua1d = 3
# (int) sides1 : Attack 1 - Damage Sides per Die
ua1sType = "integer"
ua1s = 7
# (unreal) spillDist1 : Attack 1 - Damage Spill Distance
usd1Type = "unreal"
usd1 = 0.1
# (unreal) spillRadius1 : Attack 1 - Damage Spill Radius
usr1Type = "unreal"
usr1 = 0.1
# (int) dmgUp1 : Attack 1 - Damage Upgrade Amount
udu1Type = "integer"
udu1 = 1
# (int) targCount1 : Attack 1 - Maximum Number of Targets
utc1Type = "integer"
utc1 = 2
# (bool) MissileHoming : Attack 1 - Projectile Homing Enabled
umh1Type = "integer"
umh1 = 1
# (int) Missilespeed : Attack 1 - Projectile Speed
ua1zType = "integer"
ua1z = 1
# (int) rangeN1 : Attack 1 - Range
ua1rType = "integer"
ua1r = 101
# (unreal) RngBuff1 : Attack 1 - Range Motion Buffer
urb1Type = "unreal"
urb1 = 250.1
# (bool) showUI1 : Attack 1 - Show UI
uwu1Type = "integer"
uwu1 = 0
# (targetList) targs1 : Attack 1 - Targets Allowed
ua1gType = "string"
ua1g = "debris,ground,item,structure,sapper,ward"
# (combatSound) weapType1 : Attack 1 - Weapon Sound
ucs1Type = "string"
ucs1 = "MetalHeavyBash"
# (weaponType) weapTp1 : Attack 1 - Weapon Type
ua1wType = "string"
ua1w = "artillery"
# (unreal) backSw2 : Attack 2 - Animation Backswing Point
ubs2Type = "unreal"
ubs2 = 0.65
# (unreal) dmgpt2 : Attack 2 - Animation Damage Point
udp2Type = "unreal"
udp2 = 0.65
# (int) Farea2 : Attack 2 - Area of Effect (Full Damage)
ua2fType = "integer"
ua2f = 1
# (int) Harea2 : Attack 2 - Area of Effect (Medium Damage)
ua2hType = "integer"
ua2h = 1
# (int) Qarea2 : Attack 2 - Area of Effect (Small Damage)
ua2qType = "integer"
ua2q = 1
# (targetList) splashTargs2 : Attack 2 - Area of Effect Targets
ua2pType = "string"
ua2p = "nonhero,none"
# (attackType) atkType2 : Attack 2 - Attack Type
ua2tType = "string"
ua2t = "pierce"
# (unreal) cool2 : Attack 2 - Cooldown Time
ua2cType = "unreal"
ua2c = 2.23
# (int) dmgplus2 : Attack 2 - Damage Base
ua2bType = "integer"
ua2b = 1
# (unreal) Hfact2 : Attack 2 - Damage Factor - Medium
uhd2Type = "unreal"
uhd2 = 0.1
# (unreal) Qfact2 : Attack 2 - Damage Factor - Small
uqd2Type = "unreal"
uqd2 = 0.1
# (unreal) damageLoss2 : Attack 2 - Damage Loss Factor
udl2Type = "unreal"
udl2 = 0.1
# (int) dice2 : Attack 2 - Damage Number of Dice
ua2dType = "integer"
ua2d = 3
# (int) sides2 : Attack 2 - Damage Sides per Die
ua2sType = "integer"
ua2s = 5
# (unreal) spillDist2 : Attack 2 - Damage Spill Distance
usd2Type = "unreal"
usd2 = 0.1
# (unreal) spillRadius2 : Attack 2 - Damage Spill Radius
usr2Type = "unreal"
usr2 = 0.1
# (int) dmgUp2 : Attack 2 - Damage Upgrade Amount
udu2Type = "integer"
udu2 = 1
# (int) targCount2 : Attack 2 - Maximum Number of Targets
utc2Type = "integer"
utc2 = 2
# (bool) MissileHoming : Attack 2 - Projectile Homing Enabled
umh2Type = "integer"
umh2 = 1
# (int) Missilespeed : Attack 2 - Projectile Speed
ua2zType = "integer"
ua2z = 1
# (int) rangeN2 : Attack 2 - Range
ua2rType = "integer"
ua2r = 501
# (unreal) RngBuff2 : Attack 2 - Range Motion Buffer
urb2Type = "unreal"
urb2 = 250.1
# (bool) showUI2 : Attack 2 - Show UI
uwu2Type = "integer"
uwu2 = 0
# (targetList) targs2 : Attack 2 - Targets Allowed
ua2gType = "string"
ua2g = "air,debris,ground,item,none,structure,ward"
# (combatSound) weapType2 : Attack 2 - Weapon Sound
ucs2Type = "string"
ucs2 = "MetalHeavyBash"
# (weaponType) weapTp2 : Attack 2 - Weapon Type
ua2wType = "string"
ua2w = "instant"
# (attackBits) weapsOn : Attacks Enabled
uaenType = "integer"
uaen = 2
# (deathType) deathType : Death Type
udeaType = "integer"
udea = 1
# (int) def : Defense Base
udefType = "integer"
udef = 1
# (defenseType) defType : Defense Type
udtyType = "string"
udty = "small"
# (int) defUp : Defense Upgrade Bonus
udupType = "integer"
udup = 1
# (int) minRange : Minimum Attack Range
uamnType = "integer"
uamn = 1
# (targetList) targType : Targeted as
utarType = "string"
utar = "ground,terrain"
# (bool) dropItems : Can Drop Items On Death
udroType = "integer"
udro = 0
# (bool) campaign : Categorization - Campaign
ucamType = "integer"
ucam = 1
# (bool) special : Categorization - Special
uspeType = "integer"
uspe = 1
# (bool) hostilePal : Display as Neutral Hostile
uhosType = "integer"
uhos = 1
# (bool) tilesetSpecific : Has Tileset Specific Data
utssType = "integer"
utss = 1
# (bool) inEditor : Placeable In Editor
uineType = "integer"
uine = 0
# (tilesetList) tilesets : Tilesets
utilType = "string"
util = "I,*"
# (bool) repulse : Group Separation - Enabled
urpoType = "integer"
urpo = 1
# (int) repulseGroup : Group Separation - Group Number
urpgType = "integer"
urpg = 1
# (int) repulseParam : Group Separation - Parameter
urppType = "integer"
urpp = 1
# (int) repulsePrio : Group Separation - Priority
urprType = "integer"
urpr = 1
# (unreal) moveHeight : Height
umvhType = "unreal"
umvh = 0.1
# (unreal) moveFloor : Height Minimum
umvfType = "unreal"
umvf = 0.1
# (int) spd : Speed Base
umvsType = "integer"
umvs = 271
# (int) maxSpd : Speed Maximum
umasType = "integer"
umas = 1
# (int) minSpd : Speed Minimum
umisType = "integer"
umis = 1
# (unreal) turnRate : Turn Rate
umvrType = "unreal"
umvr = 0.6
# (moveType) movetp : Type
umvtType = "string"
umvt = "horse"
# (unreal) buffRadius : AI Placement Radius
uabrType = "unreal"
uabr = 0.1
# (aiBuffer) buffType : AI Placement Type
uabtType = "string"
uabt = "buffer"
# (unreal) collision : Collision Size
ucolType = "unreal"
ucol = 32.1
# (unreal) AGIplus : Agility per Level
uagpType = "unreal"
uagp = 1.1
# (int) bldtm : Build Time
ubldType = "integer"
ubld = 54
# (bool) canFlee : Can Flee
ufleType = "integer"
ufle = 0
# (int) fused : Food Cost
ufooType = "integer"
ufoo = 4
# (int) fmade : Food Produced
ufmaType = "integer"
ufma = 1
# (int) formation : Formation Rank
uforType = "integer"
ufor = 1
# (int) bountyplus : Gold Bounty Awarded - Base
ubbaType = "integer"
ubba = 31
# (int) bountydice : Gold Bounty Awarded - Number of Dice
ubdiType = "integer"
ubdi = 9
# (int) bountysides : Gold Bounty Awarded - Sides per Die
ubsiType = "integer"
ubsi = 4
# (int) goldcost : Gold Cost
ugolType = "integer"
ugol = 426
# (bool) hideHeroDeathMsg : Hero - Hide Hero Death Message
uhhdType = "integer"
uhhd = 1
# (bool) hideHeroBar : Hero - Hide Hero Interface Icon
uhhbType = "integer"
uhhb = 1
# (bool) hideHeroMinimap : Hero - Hide Hero Minimap Display
uhhmType = "integer"
uhhm = 1
# (bool) hideOnMinimap : Hide Minimap Display
uhomType = "integer"
uhom = 1
# (int) HP : Hit Points Maximum (Base)
uhpmType = "integer"
uhpm = 101
# (unreal) regenHP : Hit Points Regeneration Rate
uhprType = "unreal"
uhpr = 2.1
# (regenType) regenType : Hit Points Regeneration Type
uhrtType = "string"
uhrt = "always"
# (unreal) INTplus : Intelligence per Level
uinpType = "unreal"
uinp = 2.6
# (bool) isbldg : Is a Building
ubdgType = "integer"
ubdg = 1
# (int) level : Level
ulevType = "integer"
ulev = 6
# (int) lumberbountyplus : Lumber Bounty Awarded - Base
ulbaType = "integer"
ulba = 1
# (int) lumberbountydice : Lumber Bounty Awarded - Number of Dice
ulbdType = "integer"
ulbd = 1
# (int) lumberbountysides : Lumber Bounty Awarded - Sides per Die
ulbsType = "integer"
ulbs = 1
# (int) lumbercost : Lumber Cost
ulumType = "integer"
ulum = 101
# (int) mana0 : Mana Initial Amount
umpiType = "integer"
umpi = 101
# (int) manaN : Mana Maximum
umpmType = "integer"
umpm = 1
# (unreal) regenMana : Mana Regeneration
umprType = "unreal"
umpr = 0.11
# (int) points : Point Value
upoiType = "integer"
upoi = 101
# (attributeType) Primary : Primary Attribute
upraType = "string"
upra = "INT"
# (int) prio : Priority
upriType = "integer"
upri = 10
# (unitRace) race : Race
uracType = "string"
urac = "critters"
# (int) goldRep : Repair Gold Cost
ugorType = "integer"
ugor = 426
# (int) lumberRep : Repair Lumber Cost
ulurType = "integer"
ulur = 101
# (int) reptm : Repair Time
urtmType = "integer"
urtm = 56
# (int) sight : Sight Radius (Day)
usidType = "integer"
usid = 1799
# (int) nsight : Sight Radius (Night)
usinType = "integer"
usin = 799
# (bool) canSleep : Sleeps
usleType = "integer"
usle = 1
# (int) stockInitial : Stock Initial After Start Delay
usitType = "integer"
usit = 2
# (int) stockMax : Stock Maximum
usmaType = "integer"
usma = 4
# (int) stockRegen : Stock Replenish Interval
usrgType = "integer"
usrg = 29
# (int) stockStart : Stock Start Delay
usstType = "integer"
usst = 1
# (unitClass) type : Unit Classification
utypType = "string"
utyp = "undead,standon"
# (unitList) DependencyOr : Dependency Equivalents
udepType = "string"
udep = "Hpal"
# (itemList) Sellitems : Items Sold
useiType = "string"
usei = "rde4"
# (techList) Requires : Requirements
ureqType = "string"
ureq = "hfoo"
# (intList) Requiresamount : Requirements - Levels
urqaType = "string"
urqa = "1"
# (unitList) Sellunits : Units Sold
useuType = "string"
useu = "hfoo,hrif"
# (unitList) Trains : Units Trained
utraType = "string"
utra = "hfoo"
# (upgradeList) upgrades : Upgrades Used
upgrType = "string"
upgr = "Rhhb"

[hfo1] # 1751543601 0x68666f31
parent = "hfoo" # 1751543663 0x68666f6f
